crates/rattler/src/channel/mod.rs, crates/rattler/src/repo_data/fetch/progress.rs
Fixes an issue with the url or named channels not containing the name of the channel.
=> fix: channel base url test

.github/workflows/rust-compile.yml, crates/rattler_package_streaming/Cargo.toml, crates/rattler_package_streaming/src/lib.rs, crates/rattler_package_streaming/src/reqwest/mod.rs, crates/rattler_package_streaming/tests/extract.rs
Extract a package from a Url with the `reqwest` feature.
=> feat: extract packages directly from urls

crates/rattler_conda_types/Cargo.toml, crates/rattler_conda_types/src/platform.rs
Be able to iterate over the Platform Enum.
=> feat: iterate over platform enum

crates/rattler_conda_types/src/platform.rs, crates/rattler_virtual_packages/Cargo.toml, crates/rattler_virtual_packages/src/cuda.rs, crates/rattler_virtual_packages/src/lib.rs, crates/rattler_virtual_packages/src/libc.rs, crates/rattler_virtual_packages/src/linux.rs, crates/rattler_virtual_packages/src/osx.rs
An API to detect virtual packages of the current platform. The implementation is largely based on the implementation of Conda.
=> feat: detect virtual packages

crates/rattler_package_streaming/src/fs.rs, crates/rattler_package_streaming/src/lib.rs
Functions to extract packages from a path.
=> feat: extract from path

LICENSE, crates/rattler-bin/Cargo.toml, crates/rattler/Cargo.toml, crates/rattler_conda_types/Cargo.toml, crates/rattler_package_streaming/Cargo.toml, crates/rattler_virtual_packages/Cargo.toml
=> misc: add licenses

crates/rattler_conda_types/src/platform.rs, crates/rattler_virtual_packages/src/lib.rs
=> feat: add riscv

crates/rattler-bin/Cargo.toml, crates/rattler-bin/src/commands/create.rs, crates/rattler_repodata_gateway/Cargo.toml, crates/rattler_repodata_gateway/src/lib.rs, crates/rattler_repodata_gateway/src/sparse/mod.rs
This implements loading specific records of the repodata instead of loading all the data, significantly improving solving performance.
=> feat: implement sparse repodata loading

crates/rattler_conda_types/Cargo.toml, crates/rattler_conda_types/src/lib.rs, crates/rattler_conda_types/src/match_spec/matcher.rs, crates/rattler_conda_types/src/match_spec/mod.rs, crates/rattler_conda_types/src/match_spec/parse.rs, crates/rattler_conda_types/src/version_spec/mod.rs
I ported over some of your code from the `pubgrub` branch, @baszalmstra :)
I should actually attribute the PR to you, sry! Would be interested what you think about the `StringMatcher` and if you have ideas on the build number matcher we might want to build.
=> Matchspec impl

crates/rattler/src/install/link.rs
Fixes an issue where backslashes should be replaced with forward slashes when replacing prefixes on windows. This is to make sure we don't accidentally introduce wrongly escaped characters if the prefix is used inside of a string literal. This works on windows since both forward- and backslashes are accepted directory separators. The same technique is employed by both micromamba and conda.
=> fix: issue with forward slash on windows

crates/rattler_conda_types/src/platform.rs, crates/rattler_virtual_packages/src/lib.rs
Adds `win-arm64` as a known platform.
=> feat: add win-arm64 as a known platform

crates/rattler_solve/Cargo.toml, crates/rattler_solve/src/lib.rs, crates/rattler_solve/src/libsolv/input.rs, crates/rattler_solve/src/libsolv/mod.rs, crates/rattler_solve/src/libsolv/wrapper/mod.rs, crates/rattler_solve/src/libsolv/wrapper/pool.rs, crates/rattler_solve/src/libsolv/wrapper/repo.rs, test-data/channels/dummy/linux-64/repodata.json
=> fix: robustly handle NUL in repodata.json

crates/rattler_solve/src/libsolv/wrapper/mod.rs, crates/rattler_solve/src/libsolv/wrapper/queue.rs, crates/rattler_solve/src/libsolv/wrapper/solvable.rs, crates/rattler_solve/src/libsolv/wrapper/solve_problem.rs, crates/rattler_solve/src/libsolv/wrapper/solver.rs
This PR parses solver problems into a vector of enums. We need to post process that list of problems into a graph, then compress it and print it to get similar error messages as with `libmamba` :)
=> Solve problems

crates/rattler_repodata_gateway/src/fetch/mod.rs
Enable downloading of `repodata_from_packages.json` with the `fetch_repo_data` function.
=> feat: enable downloading repodata_from_patches.json

crates/rattler_conda_types/src/lib.rs, crates/rattler_conda_types/src/repo_data/mod.rs, crates/rattler_conda_types/src/repo_data/patches.rs
Adds datastructures for repodata patches
=> feat: add datastructures for repodata patches

crates/rattler_conda_types/src/repo_data/patches.rs, crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__patches__test__null_values.snap
Make sure that entries that are "null" are still stored correctly.
=> fix: null values are still values

crates/rattler_conda_types/src/package/mod.rs, crates/rattler_conda_types/src/package/package_metadata.rs, crates/rattler_package_streaming/Cargo.toml, crates/rattler_package_streaming/src/lib.rs, crates/rattler_package_streaming/src/write.rs, crates/rattler_package_streaming/tests/write.rs
This adds some low-level package write functions. Unfortunately the zstd writing doesn't work for some reason (seems to write a partial file for the first file and 0 bytes for the second) and I don't know why :)
=> add package writing functions

crates/rattler_conda_types/src/platform.rs
Tried to run rattler in a devcontainer on a M1 :)
=> add more targets to target detection

crates/rattler_conda_types/Cargo.toml, crates/rattler_conda_types/src/package/index.rs, crates/rattler_conda_types/src/repo_data/mod.rs, crates/rattler_conda_types/src/utils/serde.rs, crates/rattler_solve/src/libsolv/input.rs
Fixes: https://github.com/mamba-org/rattler/issues/140
=> feat: use chrono timestamps

crates/rattler_conda_types/src/match_spec/parse.rs
Fixes: https://github.com/mamba-org/rattler/issues/97
=> fix: allow matchspec key value without quotes

crates/rattler-bin/src/commands/create.rs
Allow not-found errors for arch specific repodata channels.
This is not the cleanest implementation but we'll have to refactor this part at some point anyway.
=> fix: allow downloading of repodata.json to fail for arch specific channels

crates/rattler_package_streaming/Cargo.toml, crates/rattler_repodata_gateway/Cargo.toml
I am not very sure about this -- would love a review :)
=> expose reqwest tls features

.github/workflows/rust-compile.yml, crates/rattler_solve/src/libsolv/wrapper/pool.rs
Refactors the CI stages to build and test for multiple (cross-platform) targets.
=> fix: refactor ci to enable building for different targets

crates/libsolv_rs/src/conda_util.rs, crates/rattler_solve/src/libsolv_rs/input.rs
cc @baszalmstra pls check – I accidentally broke the main branch.
=> fix compilation in main branch

crates/libsolv_rs/src/pool.rs, crates/rattler_solve/benches/bench.rs
Reduced the sample size to 10 for solver benchmarks.
=> misc: reduce sample count for solver benchmarks

crates/rattler_shell/src/shell/mod.rs, crates/rattler_shell/src/shell/snapshots/rattler_shell__shell__tests__fish.snap, crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__activation_script_fish.snap
Fix how we set variables in fish script
=> fix: fish format variable

crates/rattler_conda_types/src/conda_lock/content_hash.rs
Fixes https://github.com/prefix-dev/pixi/issues/247
=> fix: superfluous quotes in lockfile

.github/workflows/python-bindings.yml, py-rattler/pixi.lock, py-rattler/pixi.toml, py-rattler/pyproject.toml, py-rattler/rattler/channel/channel.py, py-rattler/rattler/channel/channel_config.py, py-rattler/rattler/match_spec/match_spec.py, py-rattler/rattler/match_spec/nameless_match_spec.py, py-rattler/rattler/platform/__init__.py, py-rattler/rattler/platform/arch.py, py-rattler/rattler/platform/platform.py, py-rattler/rattler/repo_data/package_record.py, py-rattler/rattler/shell/shell.py, py-rattler/rattler/version/version.py, py-rattler/tests/unit/test_version.py
Adds `mypy` checks to `py-rattler` and fixes all existing mypy errors.
=> feat: add mypy

.github/workflows/python-bindings.yml, py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/pixi.toml, py-rattler/rattler/__init__.py, py-rattler/rattler/networking/__init__.py, py-rattler/rattler/networking/authenticated_client.py, py-rattler/src/lib.rs, py-rattler/src/networking/mod.rs
Adds the AuthenticatedClient to py-rattler from #311
=> feat: Add AuthenticatedClient to py-rattler

pixi.toml
considering also adding `cargo` task
=> expose other cargo commands

py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/rattler/__init__.py, py-rattler/rattler/networking/fetch_repo_data.py, py-rattler/rattler/repo_data/__init__.py, py-rattler/rattler/repo_data/sparse.py, py-rattler/src/lib.rs, py-rattler/src/networking/mod.rs, py-rattler/src/repo_data/mod.rs, py-rattler/src/repo_data/sparse.rs, py-rattler/tests/unit/test_fetch_repo_data.py
This would allow more functionality as well as speed up the loading of repodata a little.
=> Use SparseRepoData in fetch_repo_data

.github/workflows/python-bindings.yml, .github/workflows/rust-compile.yml, crates/rattler_libsolv_c/Cargo.toml
The code was no longer build when pushing to the main branch!
=> fix: build on main branch

crates/rattler_conda_types/src/package/paths.rs, crates/rattler_conda_types/src/package/snapshots/rattler_conda_types__package__paths__test__paths_sorted.snap, crates/rattler_conda_types/src/prefix_record.rs, crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__menuinst-1_4_19-py311h1ea47a8_1_json.snap, crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__pysocks-1_7_1-pyh0701188_6_json.snap, crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__requests-2_28_2-pyhd8ed1ab_0_json.snap, crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__urllib3-1_26_14-pyhd8ed1ab_0_json.snap, crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__xz-5_2_6-h8d14728_0_json.snap, crates/rattler_conda_types/src/utils/serde.rs
Make sure that when we write (relative) file paths, we normalize them.
=> fix: always write paths normalized

crates/rattler_shell/src/shell/mod.rs
Recursively look at the parent process until we detect a valid shell.
Fix #362
=> fix: recursive look for parent process name

.github/workflows/release-python.yml, .github/workflows/rust-compile.yml, crates/rattler_conda_types/src/platform.rs
With the release of `ring v0.17` we should now be able to target a lot more targets. Lets try!
=> feat: enable powerpc and s390x

crates/rattler_digest/src/serde.rs, crates/rattler_lock/src/lib.rs, crates/rattler_lock/src/serde.rs
This might help the user
Would close https://github.com/prefix-dev/pixi/issues/504
=> improve lockfile version mismatch error

crates/rattler_conda_types/src/match_spec/mod.rs
I wasn't able to recreate this in the tests but this is needed to fix the issue in pixi.
=> fix: set a serde default

.github/workflows/docs.yaml, .github/workflows/python-bindings.yml, py-rattler/docs/stylesheets/extra.css, py-rattler/mkdocs.yml, py-rattler/pixi.lock, py-rattler/pixi.toml
@Wackyator are the Python reference docs generated somehow? Because it might be nice to change the table layout a little bit (some of the descriptions are pretty squished now).
=> docs: update look

crates/rattler/src/install/apple_codesign.rs, crates/rattler/src/install/link.rs, crates/rattler/src/install/mod.rs
This PR adds:
- Slightly better error messages when weird io errors happen during linking
- Falling back to copying when hardlinking or symlinking fails
- An improved method to determine if hardlinking is possible.
=> feat: better detection of hardlinks and fallback to copy

crates/rattler_networking/src/authentication_storage/backends/keyring.rs
Closes https://github.com/prefix-dev/pixi/issues/631
=> only return Ok(None) on Err(keyring::Error::NoEntry)

Cargo.toml, crates/async_http_range_reader/Cargo.toml, crates/rattler-bin/Cargo.toml, crates/rattler/Cargo.toml, crates/rattler_conda_types/Cargo.toml, crates/rattler_digest/Cargo.toml, crates/rattler_index/Cargo.toml, crates/rattler_libsolv_c/Cargo.toml, crates/rattler_lock/Cargo.toml, crates/rattler_macros/Cargo.toml, crates/rattler_networking/Cargo.toml, crates/rattler_package_streaming/Cargo.toml, crates/rattler_repodata_gateway/Cargo.toml, crates/rattler_shell/Cargo.toml, crates/rattler_solve/Cargo.toml, crates/rattler_virtual_packages/Cargo.toml, crates/tools/Cargo.toml
Fix https://github.com/mamba-org/rattler/issues/481
=> chore: move all dependencies to workspace

Cargo.toml
This should fix the build failure on main.
=> fix: update pep440 dependency to fix build failure

Cargo.toml, crates/rattler_conda_types/Cargo.toml, crates/rattler_solve/Cargo.toml
Fixes the build issue on main and sort the dependencies in the workspace Cargo.toml
=> fix: remove dependency on native-tls

Cargo.toml, crates/rattler_lock/src/builder.rs, crates/rattler_lock/src/lib.rs, crates/rattler_lock/src/parse/deserialize.rs, crates/rattler_lock/src/parse/mod.rs, crates/rattler_lock/src/parse/serialize.rs, crates/rattler_lock/src/parse/v3.rs, crates/rattler_lock/src/pypi.rs, crates/rattler_lock/src/utils/serde/pep440_map_or_vec.rs, py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/src/lock/mod.rs
=> chore: bump pep508_rs and pep440_rs

Cargo.toml, crates/rattler/src/install/clobber_registry.rs, crates/rattler_solve/tests/backends.rs
=> fix: removal of multiple packages that clobber each other

Cargo.toml, crates/rattler_conda_types/src/utils/serde.rs, crates/rattler_lock/src/utils/serde/timestamp.rs, crates/rattler_repodata_gateway/src/fetch/mod.rs
Fixes `chrono` deprecation warnings introduced in 0.4.35.
=> fix: chrono deprecation warnings

crates/rattler_networking/src/authentication_storage/backends/netrc.rs, crates/rattler_networking/src/authentication_storage/storage.rs
We were early-exiting the loop.
=> fix: properly fall back to netrc file

crates/rattler_lock/src/lib.rs, crates/rattler_lock/src/url_or_path.rs, test-data/conda-lock/absolute-path-lock.yml
=> fix: issue 615

py-rattler/Cargo.lock, py-rattler/pixi.lock, py-rattler/pixi.toml, py-rattler/rattler/lock/lock_file.py, py-rattler/rattler/prefix/prefix_paths.py
Fixes an error in CI when testing py-rattler for python 3.8.
=> fix: ABCMeta is not subscriptable

crates/rattler-bin/Cargo.toml, crates/rattler/CHANGELOG.md, crates/rattler/Cargo.toml, crates/rattler_index/CHANGELOG.md, crates/rattler_index/Cargo.toml, crates/rattler_lock/CHANGELOG.md, crates/rattler_lock/Cargo.toml, crates/rattler_networking/CHANGELOG.md, crates/rattler_networking/Cargo.toml, crates/rattler_package_streaming/CHANGELOG.md, crates/rattler_package_streaming/Cargo.toml, crates/rattler_repodata_gateway/CHANGELOG.md, crates/rattler_repodata_gateway/Cargo.toml
* `rattler_networking`: 0.20.3 -> 0.20.4 (✓ API compatible changes)
* `rattler_lock`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `rattler_repodata_gateway`: 0.19.9 -> 0.19.10 (✓ API compatible changes)
* `rattler_index`: 0.19.8 -> 0.19.9 (✓ API compatible changes)
* `rattler`: 0.23.1 -> 0.23.2
* `rattler_package_streaming`: 0.20.6 -> 0.20.7
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- bump py-rattler 0.5.0 ([#629](https://github.com/mamba-org/rattler/pull/629))
</blockquote>
<blockquote>
- adds pypi indexes to the lock-file ([#626](https://github.com/mamba-org/rattler/pull/626))
</blockquote>
<blockquote>
- create SparseRepoData from byte slices ([#624](https://github.com/mamba-org/rattler/pull/624))
</blockquote>
<blockquote>
- release …
=> chore: release

Cargo.toml, crates/rattler_lock/src/utils/serde/pep440_map_or_vec.rs, py-rattler/Cargo.lock, py-rattler/Cargo.toml
=> chore: bump pep crates

crates/rattler_repodata_gateway/src/gateway/query.rs, crates/rattler_solve/src/lib.rs, crates/rattler_solve/src/libsolv_c/input.rs, crates/rattler_solve/src/libsolv_c/mod.rs, crates/rattler_solve/src/resolvo/mod.rs, crates/rattler_solve/tests/backends.rs
Fixes an issue with duplicate records in the solver.
=> fix: result grouped by subdir instead of channel

py-rattler/Cargo.lock, py-rattler/rattler/package/index_json.py, py-rattler/rattler/repo_data/package_record.py, py-rattler/src/index_json.rs, py-rattler/src/record.rs
fixes #700 
It's a breaking change though!
=> feat: keep full timestamp precision and return datetime.datetime

crates/rattler_solve/Cargo.toml
https://docs.rs/about/metadata
https://docs.rs/rattler_solve/0.24.2/rattler_solve/index.html#modules
Same as what tokio does:
https://github.com/tokio-rs/tokio/blob/341b5daa6e4592d285674de4eb116c928fc9f29c/tokio/Cargo.toml#L157C1-L158
=> docs: Document all features on docs.rs

Cargo.toml, crates/rattler_solve/src/resolvo/mod.rs, py-rattler/Cargo.lock, tools/create-resolvo-snapshot/Cargo.toml, tools/create-resolvo-snapshot/README.md, tools/create-resolvo-snapshot/src/main.rs
Adds a tool to create a resolvo snapshot from a conda channel.
=> feat: add tool to generate resolvo snapshots

crates/rattler_conda_types/src/repo_data/mod.rs, crates/rattler_repodata_gateway/src/sparse/mod.rs
I didn't benchmark this - but I don't think it should have a huge impact. 
LMK what you think, Mr. Bas!
=> fix: allow empty json repodata

.github/workflows/rust-compile.yml, crates/rattler_conda_types/src/match_spec/mod.rs
Cargo nextest doesn't run doctest so we missed that: https://github.com/nextest-rs/nextest/issues/16
=> fix: Fix doctests and start testing them again

crates/rattler_virtual_packages/src/libc.rs
=> fix: add gentoo support for glibc

Cargo.toml, crates/rattler_solve/src/resolvo/conda_util.rs, crates/rattler_solve/src/resolvo/mod.rs, py-rattler/Cargo.lock
=> chore: bump resolvo to 0.7.0

crates/rattler_conda_types/src/match_spec/parse.rs, crates/rattler_repodata_gateway/src/gateway/error.rs, crates/rattler_repodata_gateway/src/gateway/local_subdir.rs, crates/rattler_repodata_gateway/src/gateway/mod.rs, crates/rattler_repodata_gateway/src/gateway/query.rs, crates/rattler_repodata_gateway/src/gateway/remote_subdir.rs, crates/rattler_repodata_gateway/src/gateway/sharded_subdir/mod.rs, crates/rattler_repodata_gateway/src/gateway/subdir.rs
will be used by new gateway for pixi search
=> feat: add package names api for gateway

crates/rattler_virtual_packages/src/libc.rs
=> fix: detect solus glibc

crates/rattler_solve/src/lib.rs
=> docs: Remove note that only libsolv is supported

crates/rattler_solve/src/resolvo/mod.rs
- Fixes https://github.com/conda/rattler/issues/830
- Didn't really find any test covering this specific code path :( but I've tested that my specific issue got solved!
=> fix: Redact spec channel before comparing it with repodata channel 

pixi.toml, scripts/activate_linux.sh
See also https://github.com/prefix-dev/pixi/pull/1914
=> feat: use mold linker on linux

crates/rattler_conda_types/src/match_spec/matcher.rs
- Adds some edge case testing for `StringMatcher` (not exactly https://github.com/conda/rattler/issues/205, but related)
=> feat: add edge case tests for `StringMatcher`

crates/rattler/src/install/installer/indicatif.rs, crates/rattler/src/install/mod.rs, crates/rattler_shell/src/shell/mod.rs, crates/rattler_solve/src/libsolv_c/libc_byte_slice.rs, py-rattler/rattler/install/installer.py, typos.toml
=> fix: remaining typos

crates/rattler_conda_types/src/generic_virtual_package.rs
@baszalmstra lmk what you think about this.
Serializes as:
```
- __cuda
- __cuda=12.0
- __cuda=12.0=abcdef
```
=> feat: add serialization for virtual packages

crates/rattler_conda_types/src/channel/mod.rs, py-rattler/Cargo.lock
Adds the possibility to use relative paths as a named channel or URL.
=> feat: add path to namedchannelorurl

crates/rattler_package_streaming/src/lib.rs
https://github.com/prefix-dev/pixi/issues/1994#issuecomment-2391415669
=> feat: Make ExtractError more informative

py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/pixi.lock, py-rattler/pixi.toml
Preparing a release of py-rattler `0.7.2`.
[Full diff](https://github.com/conda/rattler/compare/py-rattler-v0.7.1...baszalmstra:bump/py-rattler-0.7.2)
=> chore: bump py-rattler 0.7.2

crates/rattler_cache/src/package_cache/cache_key.rs, crates/rattler_cache/src/package_cache/cache_lock.rs, crates/rattler_cache/src/package_cache/mod.rs
=> feat: use sha in cache lock file, needed for source builds.

Cargo.toml, crates/file_url/Cargo.toml, crates/rattler-bin/Cargo.toml, crates/rattler_libsolv_c/Cargo.toml, crates/rattler_networking/Cargo.toml, crates/rattler_networking/src/gcs_middleware.rs, crates/rattler_networking/src/lib.rs, crates/rattler_shell/Cargo.toml, crates/rattler_shell/src/shell/mod.rs
Just a periodic update of everything. Going to test the incompatible updates as well.
=> chore: update all versions of packages

crates/rattler_lock/src/lib.rs
Solves this [issue](https://github.com/conda/rattler/issues/920)
=> feat: add debug trait to LockFile struct in rattler_lock

py-rattler/rattler/networking/client.py
=> fix: Docstring in authenticated_client

crates/rattler_repodata_gateway/src/gateway/mod.rs, crates/rattler_repodata_gateway/src/gateway/query.rs, py-rattler/rattler/package/package_name.py, py-rattler/rattler/repo_data/gateway.py, py-rattler/tests/unit/test_gateway.py
Fix an issue where all records where returned by the gateway even when they didnt match the root specs when using recursive mode.
=> fix: gateway recursive records

crates/rattler_shell/Cargo.toml, crates/rattler_shell/src/activation.rs, crates/rattler_shell/src/run/mod.rs
=> feat: use fs-err in rattler_shell

crates/rattler_networking/src/oci_middleware.rs, py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/pixi.lock, py-rattler/pixi.toml, py-rattler/rattler/networking/client.py, py-rattler/rattler/networking/middleware.py, py-rattler/rattler/package/about_json.py, py-rattler/rattler/package/index_json.py, py-rattler/rattler/package_streaming/__init__.py, py-rattler/src/about_json.rs, py-rattler/src/index_json.rs, py-rattler/src/lib.rs, py-rattler/src/networking/client.rs, py-rattler/src/networking/middleware.rs, py-rattler/src/package_streaming/mod.rs, py-rattler/tests/unit/test_package_streaming.py
Adds a number of setters and tests.
=> feat: more setters for about.json and index.json 

crates/rattler_conda_types/src/channel/mod.rs
That is needed for https://github.com/prefix-dev/pixi/pull/2702
=> feat: derive `PartialEq` and `Eq` for `ChannelConfig`

crates/rattler_lock/src/lib.rs, test-data/conda-lock/v6/empty-lock.yml
Convenience function I would like to use in `pixi`
=> feat: add a check function for empty lockfiles

.github/workflows/docs.yaml, .github/workflows/pre-commit.yaml, .github/workflows/release-rust.yaml
I am trying to 100% get rid of LFS to make our release CI unstuck.
=> chore: remove lfs completely

py-rattler/Cargo.lock, py-rattler/rattler/lock/environment.py, py-rattler/src/lock/mod.rs, py-rattler/tests/unit/test_prefix_record.py
=> fix: add channels to constructor of Environment

crates/rattler_conda_types/Cargo.toml, crates/rattler_conda_types/src/prefix_record.rs
This should help when we hit issues with empty files.
=> feat: write prefix record atomically

js-rattler/package-lock.json, js-rattler/package.json, js-rattler/src/Version.ts, js-rattler/webpack.config.mjs
we only build umd output, which doesn't with with esm only environment. this add esm target.
=> build(js): add esm output

crates/rattler_repodata_gateway/src/gateway/query.rs
=> fix: split matchspec on start of constraint

crates/rattler_menuinst/Cargo.toml
Add required version to dependencies and add changelog
=> fix: release-plz

py-rattler/Cargo.lock, py-rattler/Cargo.toml, py-rattler/pixi.lock, py-rattler/pixi.toml, py-rattler/src/about_json.rs, py-rattler/src/index_json.rs, py-rattler/src/lib.rs, py-rattler/src/lock/mod.rs, py-rattler/src/match_spec.rs, py-rattler/src/nameless_match_spec.rs, py-rattler/src/networking/mod.rs, py-rattler/src/package_streaming/mod.rs, py-rattler/src/paths_json.rs, py-rattler/src/prefix_paths.rs, py-rattler/src/record.rs, py-rattler/src/repo_data/gateway.rs, py-rattler/src/shell.rs, py-rattler/src/solver.rs, py-rattler/src/version/component.rs
Trying to get `main` green again :)
=> chore: update pyo3

Cargo.toml, crates/rattler_index/Cargo.toml, crates/rattler_index/src/main.rs, py-rattler/Cargo.lock
=> fix: Code review in rattler-index and test fix

README.md
=> docs: Fix badge style

.github/workflows/python-bindings.yml, .github/workflows/rust-compile.yml, crates/rattler_networking/tests/s3_integration_test.rs, py-rattler/tests/unit/test_index.py
=> fix: R2 key names

Cargo.lock, crates/rattler_menuinst/src/windows.rs
Started a method so that we can create / use "fake" folders on Windows for easier testing on the pixi side.
=> feat: add fake folders method on win

crates/rattler_pty/CHANGELOG.md, crates/rattler_pty/Cargo.toml, crates/rattler_pty/src/lib.rs, crates/rattler_pty/src/unix/mod.rs, crates/rattler_pty/src/unix/pty_process.rs, crates/rattler_pty/src/unix/pty_session.rs, crates/rattler_pty/tests/integration_test.rs
This PR addresses this https://github.com/conda/rattler/issues/1067 via first porting over pixi pty crate tor rattler
i moved the tests to its own file
=> feat: port over pixi pty crate to rattler  (1/n)

CONTRIBUTING.md, py-rattler/rattler/virtual_package/virtual_package.py
=> docs: Mention deprecated detect function and the need for submodule init

crates/rattler_index/src/lib.rs
we should retry failed network connections a couple of times
=> feat: Add retry middleware to opendal operator

py-rattler/docs/index_.md, py-rattler/mkdocs.yml, py-rattler/rattler/index/index.py
Add `rattler.index` to documentation, fixes #1183
=> docs: add rattler.index (#1183)

py-rattler/docs/index.md
=> docs: Fix link

Cargo.lock, crates/rattler_libsolv_c/Cargo.toml, crates/rattler_libsolv_c/build.rs, crates/rattler_libsolv_c/src/lib.rs, crates/tools/src/libsolv_bindings.rs
Bump libsolv to 0.7.31 to fix incompatibility with cmake 4.0.
=> feat: bump libsolv to 0.7.31

crates/rattler_conda_types/src/match_spec/mod.rs, crates/rattler_conda_types/src/match_spec/parse.rs, crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__matchspec_to_string.snap, crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__tests__serialize_matchspec.snap, py-rattler/rattler/match_spec/match_spec.py
needed for https://github.com/conda-incubator/conda-mirror/pull/76
=> feat: Add license to MatchSpec

crates/rattler_conda_types/src/match_spec/mod.rs
=> fix: MatchSpec matches if license is set

Cargo.lock, crates/rattler_pty/src/unix/pty_process.rs, crates/rattler_pty/src/unix/pty_session.rs, crates/rattler_shell/Cargo.toml, crates/rattler_shell/src/activation.rs
This PR addresses this issue https://github.com/conda/rattler/issues/1067 via first porting over `start_unix_shell` https://github.com/prefix-dev/pixi/blob/e42014a51fda9fb7b39b37d8548089a006b4f5bc/src/cli/shell.rs#L134 from pixi
Follow up of this PR https://github.com/conda/rattler/pull/1074
I tried to add the unit tests but since the CI does not have a shell env, the CI will fail. Also, after running the tests, the terminal can also be messed up.
it also fixes a few lint errors
cc @baszalmstra @iamthebot
=> feat: Add start_unix_shell in Activator (2/n)

Cargo.lock, Cargo.toml, crates/rattler_cache/src/run_exports_cache/mod.rs, crates/rattler_conda_types/src/package/about.rs, crates/rattler_conda_types/src/package/index.rs, crates/rattler_conda_types/src/package/paths.rs, crates/rattler_conda_types/src/package/run_exports.rs, crates/rattler_menuinst/src/linux.rs, crates/rattler_menuinst/src/macos.rs, crates/rattler_repodata_gateway/src/fetch/with_cache.rs, py-rattler/Cargo.lock
=> chore: Bump zip to 3.0.0

py-rattler/examples/install_to_prefix.py, py-rattler/rattler/__init__.py, py-rattler/rattler/package/__init__.py, py-rattler/rattler/package/no_arch_type.py, py-rattler/rattler/platform/platform.py, py-rattler/rattler/prefix/__init__.py, py-rattler/rattler/prefix/prefix_record.py, py-rattler/rattler/repo_data/package_record.py, py-rattler/src/installer.rs, py-rattler/src/lib.rs, py-rattler/src/record.rs, py-rattler/tests/unit/test_package_record.py
=> fix(py): constructor and type issues

crates/rattler-bin/Cargo.toml, crates/rattler/Cargo.toml, crates/rattler_cache/Cargo.toml, crates/rattler_networking/Cargo.toml, crates/rattler_package_streaming/Cargo.toml, crates/rattler_repodata_gateway/Cargo.toml
=> chore: add rustls-tls / nativetls feature to rattler_cache

Cargo.lock, py-rattler/Cargo.toml
=> chore: release py-rattler 0.14.0

.github/workflows/rust-compile.yml
CI was consistently [running out of disk space](https://github.com/conda/rattler/actions/runs/15796820572/job/44529948183?pr=1418#step:12:652). Hopefully, this fixes that.
=> fix: disk space issues during build

Cargo.lock, crates/rattler_shell/src/shell/mod.rs
=> fix: simplify validate env vars

.github/workflows/rust-compile.yml, Cargo.lock, crates/rattler_config/src/config/concurreny.rs, crates/rattler_config/src/config/proxy.rs, crates/rattler_config/src/config/repodata_config.rs, crates/rattler_config/src/config/s3.rs, crates/rattler_index/Cargo.toml, crates/rattler_index/src/lib.rs, crates/rattler_index/src/main.rs, crates/rattler_networking/Cargo.toml, py-rattler/Cargo.toml, py-rattler/rattler/index/index.py, py-rattler/src/index.rs
closes #1288
i decided to not include mirror config as this really doesn't make much sense in rattler-index (at the moment)
closes #1153
=> feat(rattler_index): Use rattler_config

Cargo.lock, Cargo.toml, crates/rattler_solve/src/resolvo/conda_sorting.rs, crates/rattler_solve/src/resolvo/mod.rs
Hey @baszalmstra, are you okay with bumping the `resolvo` dependency version?
=> refactor: `resolvo` bump

crates/rattler/src/cli/auth.rs
Unfortunately we hit some issue when trying to log in with 
```
pixi auth login --token 'DUMMY_TOKEN' https://prefix.dev/
```
Because it tries to call an endpoint at `https://https//prefix.dev//api/graphql` which doesn't work.
The naming of `host` is a bit misleading here as we are feeding in the unsanitized argument from the CLI.
=> fix: logic to get to `prefix.dev` host

pixi.toml
The false-positive chance is too high IMO
=> chore: don't autofix typos

py-rattler/Cargo.lock, py-rattler/Cargo.toml
=> chore: Bump py-rattler to 0.16.0

crates/rattler_cache/src/package_cache/mod.rs
We encountered some packages that have a wrong md5 hash but a correct sha256. We used to check both and error if the hash of the downloaded package is different than what we expect (read from the repodata).
With this change, we only check the best cryptographic one. So sha256 if it exists and otherwise md5.
=> fix: ignore md5 hash if sha256 already matches

crates/rattler_upload/src/upload/s3.rs
Adds custom metadata with the sha256 and md5 hash of a package during uploading, which will allow us to not have to stream the entire file when we index. This PR also changes the way we upload to a streaming approach, which should reduce the memory requirements of uploading very large packages.
=> feat(upload): attach hashes to uploaded packages

crates/rattler_virtual_packages/src/lib.rs
Unfortunately we had to pull the latest `rattler-build` release because the change in virtual packages tripped up a lot of conda-forge pipelines.
The real fix (as discussed on [Zulip](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Missing.20virtual.20packages.20when/with/543675934)[#general > Missing virtual packages when](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Missing.20virtual.20packages.20when/with/543675934)) would be to add `system-requirements` to the recipes.
However, to mimic the previous behavior, we're now using the "detected" virtual package from the host as fallback instead of always falling back to version "0" for things.
Note that env vars should still override the virtual packages just fine (although that is not fine …
=> fix: use defaults found on OS even if cross-compiling
