crates/rattler/Cargo.toml
crates/rattler/src/commands/create.rs
crates/rattler/src/main.rs

Moves from `structopt` to latest version of `clap`

refactor: move to clap

---

.github/workflows/rust-compile.yml
crates/rattler/src/platform.rs

Some CI improvements:
* Only build when pushing to default branch *or* for pull_requests.
* Use [`clippy-check`](https://github.com/actions-rs/clippy-check) for clippy to get better output in log.
* Cancel previous running CI job if new commits are pushed
* Adds a build matrix to build on all supported platforms
* Ensures cargo always outputs colors
* Fix an issue with MacOS builds!

feat(ci): build on pull_request or push to main

---

.gitattributes
crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/data/conda-22.11.1-py38haa244fe_1.conda
crates/rattler_package_streaming/data/conda-22.9.0-py38haa244fe_2.tar.bz2
crates/rattler_package_streaming/data/mamba-1.0.0-py38hecfeebb_2.tar.bz2
crates/rattler_package_streaming/data/mamba-1.1.0-py39hb3d9227_2.conda
crates/rattler_package_streaming/data/micromamba-1.1.0-0.tar.bz2
crates/rattler_package_streaming/data/mujoco-2.3.1-ha3edaa6_0.conda
crates/rattler_package_streaming/data/pytweening-1.0.4-pyhd8ed1ab_0.tar.bz2
crates/rattler_package_streaming/data/ros-noetic-rosbridge-suite-0.11.14-py39h6fdeb60_14.tar.bz2
crates/rattler_package_streaming/data/ruff-0.0.171-py310h298983d_0.conda
crates/rattler_package_streaming/data/stir-5.0.2-py38h9224444_7.conda
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/read.rs
crates/rattler_package_streaming/src/seek.rs
crates/rattler_package_streaming/tests/extract.rs

First part of rust package streaming. This is still missing tests. This initial PR only provides a sync `Read` implementation. Later additions could provide more functionality with `Seek` support and an async implementation needed for `micromamba`.
The `.tar.bz2` extract process uses parallel decoded `bzip2` which is extremely fast.

feat: sync extraction of existing package formats

---

crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_package_streaming/src/tokio/async_read.rs
crates/rattler_package_streaming/src/tokio/mod.rs
crates/rattler_package_streaming/tests/extract.rs

Async methods to extract conda packages. 
Until we find a better library to do async tar and zip archive handling this code wraps the sync code in an async context with [`SyncIoBridge`](https://docs.rs/tokio-util/latest/tokio_util/io/struct.SyncIoBridge.html).
I briefly benchmarked the code which resulted in:
|                 | sync       | async      |       |
|-----------------|------------|------------|-------|
| extract_conda   | **5.725s** | 5.965s     | +4.1% |
| extract_tar_bz2 | **2.424s** | 2.515s     | +3.7% |
| extract_url     | 9.694s     | **9.359s** | -3.5% |
All in all, I think these results are good enough to merge the async functions.

feat: async extraction methods

---

crates/rattler/Cargo.toml
crates/rattler/src/lib.rs
crates/rattler/src/package_cache.rs
crates/rattler/src/package_store.rs
crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/fs.rs
crates/rattler_package_streaming/src/tokio/fs.rs
crates/rattler_package_streaming/src/tokio/mod.rs

Provides functionality to cache extracted Conda packages in a directory. The cache object holds an in-memory cache of which valid packages exist. It checks the filesystem if an entry doesn't exist in memory yet. Validation (from #39 ) is used to determine whether the cache is corrupt. If the filesystem also doesn't provide the requested package it is fetched into the cache.
The cache does not provide a method to download and extract package archives but instead relies on a `populate` function. The goal is to decouple "caching" and "download/extract". This makes it easier to test, provide different downloading functionalities, queueing, etc.
Builds on #39 which should be merged first!

feat: package cache

---

crates/rattler/src/solver/libsolv/mod.rs
crates/rattler/src/solver/libsolv/pool.rs
crates/rattler/src/solver/libsolv/repo.rs
crates/rattler/src/solver/mod.rs

This commit makes sure we allow calling libsolv functions from shared references, instead of requiring mutability, because otherwise legitimate use cases of the library (like multiple repos for a single pool) are impossible to express.

Polish libsolv ffi wrapper

---

crates/rattler_conda_types/src/package/index.rs
crates/rattler_conda_types/src/package/mod.rs
crates/rattler_conda_types/src/package/snapshots/rattler_conda_types__package__index__test__reconstruct_index_json.snap
crates/rattler_conda_types/src/package/snapshots/rattler_conda_types__package__index__test__reconstruct_index_json_with_symlinks.snap

Two things I found while writing / adjusting this code:
- to my knowledge, run_exports are defined in a seperate file (`info/run_exports.json`) so I was surprised to see this in the index.json definition. Did you encounter a package where run_exports were added to the index? Otherwise I would suggest we remove that for now?
- The `paths.json` object is called `PathsJson` while the `index.json` object is called `Index`. Should we make them both the same?
Also, I've used `serde_json::from_reader(...)` instead of going via reading a string and reusing the FromStr functions. That means we have two `.map_err(Into::into)`. Let me know if you prefer the `FromStr` way.

move index to its own file, add helper functions and simple test

---

crates/rattler/src/package_cache.rs
crates/rattler/src/validation.rs
crates/rattler_conda_types/src/channel_data.rs
crates/rattler_conda_types/src/package/about.rs
crates/rattler_conda_types/src/package/files.rs
crates/rattler_conda_types/src/package/has_prefix.rs
crates/rattler_conda_types/src/package/index.rs
crates/rattler_conda_types/src/package/mod.rs
crates/rattler_conda_types/src/package/no_link.rs
crates/rattler_conda_types/src/package/no_softlink.rs
crates/rattler_conda_types/src/package/paths.rs
crates/rattler_conda_types/src/package/run_exports.rs
crates/rattler_conda_types/src/run_export.rs

Adds `PackageFile` trait that implements common functionality for files that are commonly found in a package archive like the `index.json` or `about.json`. 
The `PackageFile` trait implements most of the deserialization functions out of the box. You only need to provide the `from_str` and  `package_path` functions.
This PR also renames types that are represented by `.json` files to include the `Json` suffix. This is to indicate that they represent the structure of these json files and are not per se generic data structures.

feat: adds the PackageFile trait for consistency

---

crates/rattler_virtual_packages/src/cuda.rs
crates/rattler_virtual_packages/src/lib.rs
crates/rattler_virtual_packages/src/libc.rs
crates/rattler_virtual_packages/src/linux.rs
crates/rattler_virtual_packages/src/osx.rs

Adds documentation to `rattler_virtual_packages` and denies undocumented public members.
One step closer to #61

chore(docs): add deny missing docs to virtual packages

---

crates/rattler_package_streaming/src/fs.rs
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/read.rs
crates/rattler_package_streaming/src/reqwest/mod.rs
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_package_streaming/src/seek.rs
crates/rattler_package_streaming/src/tokio/async_read.rs
crates/rattler_package_streaming/src/tokio/fs.rs
crates/rattler_package_streaming/src/tokio/mod.rs

Adds documentation to `rattler_package_streaming` and denies undocumented public members.
One step closer to #61

chore(docs): add deny missing docs to package streaming

---

crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/fetch/mod.rs

Fixes an issue where the cache was always out of date because the check was reversed. 🙈 
Code taken from https://github.com/mamba-org/rattler/pull/72 to split it up a bit.

fix: repodata cache was always out of date

---

crates/rattler/src/package_cache.rs
crates/rattler/src/validation.rs

Updates package cache validation code to also check that a valid `index.json` file exists. The parsed files are also returned so you don't have to reparse them.
Code taken from #72 to split it up a bit.

fix: validate index.json file

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/mod.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/version/mod.rs
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/libsolv/wrapper/pool.rs

I think we should attribute the original conda documentation/files that these were taken from. 
@baszalmstra do you want to check the matchspec parsing? some of the examples didn't work because of a `BracketsError`.

matchspec & version docs

---

crates/rattler_repodata_gateway/src/sparse/mod.rs

Fixes an issue where the sparse index loader returns duplicate records if you mention the same package multiple times.

fix: sparse index returns duplicate records

---

crates/rattler_conda_types/src/channel_data.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_solve/src/lib.rs

Adds some fields that were missing from package records. 
Also made the version and timestamp of channeldata packages optional since apparently, they don't all contain those fields..

feat: add some missing fields

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/sparse/mod.rs

* Sometimes `repodata.json` files dont include the `subdir` field for their entries. This PR adds this information back when using the sparse index.
* Adds a method to query the package names that exist in a spare repodata.json file.
* Adds a method to download only the entries for a specific package without also loading its dependencies.
* Renamed some functions to include the recursive nature.

feat: extra methods to query spare repodata

---

crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/sparse/mod.rs

Fixes an issue where records from other packages were returned when searching the sparse index.
See the explanation in the code.

fix: sort entries by package name in sparse index

---

crates/rattler_conda_types/src/no_arch_type.rs

Fixes: #129 
This PR adds several methods to construct the `NoArchType` struct.

feat: construction methods for NoArchType

---

crates/rattler/src/install/link.rs
crates/rattler_conda_types/src/package/mod.rs
crates/rattler_conda_types/src/package/paths.rs
crates/rattler_conda_types/src/package/snapshots/rattler_conda_types__package__paths__test__reconstruct_paths_json.snap
crates/rattler_conda_types/src/package/snapshots/rattler_conda_types__package__paths__test__reconstruct_paths_json_with_symlinks.snap

@wolfv figured out that the `file_mode` is only set if the `prefix_placeholder` is set. This makes sense since the file_mode refers to how the placeholder should be interpreted in the file.
To make this more explicit I pulled out both fields and added a new type `PrefixPlaceholder` that combines the two. This means they are either both set or not at all. Using `serde(flatten)` the structure of the file remains the same.
Supersedes #132

fix: couple file_mode and prefix_placeholder

---

crates/rattler_conda_types/src/repo_data/mod.rs

This helps with repodata patching :)

add Clone to repodata

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_package_streaming/tests/write.rs

Uses platform and architecture and values that were found in the production database.

feat: now determines subdir

---

crates/rattler_shell/src/activation.rs

I need the computed PATH for stacking of environments. Would be curious what you think about this API @baszalmstra?

return path and script from activation command

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_solve/Cargo.toml
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/libsolv/input.rs

Fixes: https://github.com/mamba-org/rattler/issues/139
Fixes: https://github.com/mamba-org/rattler/issues/134

feat: use digest in repodata

---

crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_package_streaming/tests/extract.rs

Unfortunately I couldn't get both the `file` and reqwest if/else branches to return the same type. I would have liked to factor out the creation of teh "stream" of data into a function, then we could keep all interfaces.

add support for local files

---

README.md
environment.yml

After having a conversation in our discord it became very obvious we should have an environment.yml that specifies the dependencies to compile Rattler.

Improve getting started with a micromamba environment.

---

README.md
environment.yml

fix: typo libsolve -> libsolv

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs

I couldn't use `ParseMatchSpecError` in another `#[derive(thiserror)]` because the module wasn't pub. We could also specifically re-export the error only at another level?
lmk what you think

make ParseError public and reuse ArchiveType

---

crates/rattler_conda_types/src/platform.rs

Note: 
- I also had a version that wrote out all options
- We could also implement a stricter type for `Arch`
- I think we should also implement a catch-all platform (`Unknown(String)`) to facilitate adding new platforms easily

Add .arch function

---

crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/write.rs
crates/rattler_package_streaming/tests/write.rs

I cobbled something together to help build "reproducible" archives. 
This deterministically sets the timestamp of all files in an archive. That worked for a quick test of building a reproducible package :)
However, we could come up with more interesting schemes of modifying the timestamps (e.g. only forcing the timestamp on files that have been written in the past 24 hours or so, and leave those files that were just copied from the source archive as they are).
Some references: https://reproducible-builds.org/docs/timestamps/

Allow setting timestamp when writing archives

---

crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/conda_lock/content_hash.rs

I extracted the Python json formatter code to a separate crate: https://github.com/prefix-dev/serde-json-python-formatter 
This PR integrates that crate.
Fixes: https://github.com/mamba-org/rattler/issues/168

feat: extract python json formatter

---

crates/rattler_repodata_gateway/Cargo.toml

When using the `sparse` feature you also need the `serde_json/raw_value` feature.

fix: sparse requires raw_value

---

crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/version_spec/mod.rs

Exposing missing types to be able to construct `VersionSpecs`.

fix: add missin spec types

---

crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_conda_types/Cargo.toml

add tls features to rattler dependencies as well

---

crates/rattler_conda_types/src/conda_lock/mod.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data_record.rs
crates/rattler_repodata_gateway/src/sparse/mod.rs

fix: small issues I encountered

---

crates/rattler_conda_types/src/conda_lock/mod.rs
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs

Nameless match spec is matchspec without a package name. This is useful when you describe specs as an object instead of as an array. Since in the matchspec syntax the name could be in several places in the text representation parsing on nameless matchspec takes on a simpler form.

feat: nameless match spec

---

crates/rattler/src/install/transaction.rs

If package records dont match exactly but they do refer to the same content the transaction considers them to be equal. This is useful because when installing from a lock file instead of from repodata the records don't completely contain the same information. However, they do contain enough information to know that they refer to the same content.

fix: less strict checking of identical packages in transaction

---

crates/rattler_shell/Cargo.toml
crates/rattler_shell/src/activation.rs
crates/rattler_shell/src/shell/mod.rs

Adds `ShellEnum`: an enum to enable "dynamic" dispatch for shell types.
Adds the possibility to discover the default shell for the current platform. (Super dumb)
Adds a method to invoke a shell script.

feat: add a dynamic shell type and simple discovery

---

crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version_spec/mod.rs

Not sure if this is the cleanest way of implementing this behavior, but in order to fix #194 we need to ignore trailing `0` when comparing versions for equality.

ignore trailing .0 in version comparison

---

.gitignore
crates/rattler_conda_types/src/version/mod.rs
crates/rattler_virtual_packages/Cargo.toml
crates/rattler_virtual_packages/src/lib.rs

Used to help with the parsing of the virtual package from toml

feature: make it possible to deserialize virtual packages

---

crates/rattler_solve/src/lib.rs

Going from :
```
error: unsolvable
```
To:
```
error: Cannot solve the request because of: nothing provides requested poopie
```

feat: add libsolve errors to error message

---

crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/version_tree.rs

Refactors parsing of version trees by replacing the regex parser with nom. Hopefully, we can reuse these parsers in other parts of the library as well.
Fix #204

refactor: version tree parsing with nom

---

crates/rattler_virtual_packages/Cargo.toml
crates/rattler_virtual_packages/src/libc.rs

Implements an alternative method to detect the *system* libc version. 
We ran into an issue that when a binary is build against musl the code was unable to detect the proper libc version of the system. The code used the libc family against which it was built instead. 
Although this implementation is less then ideal because it assumes a few things I think its good enough for now.

feat: alternative libc detection

---

crates/rattler_conda_types/src/match_spec/parse.rs

I made the mistake of adding `=>1.2.3` which is very much illegal but it was not really clear from the error message

improve version parse error msg

---

crates/rattler_conda_types/src/conda_lock/builder.rs
crates/rattler_conda_types/src/conda_lock/mod.rs
crates/rattler_conda_types/src/platform.rs
crates/rattler_conda_types/src/utils/serde.rs

This adds some small changes to the conda-lock code to:
* Use FXhash for maps
* Add `Eq`, `PartialEq`, `Clone`, `Debug`, `Hash` to datastructures that support it.
* Add the `Ordered<_>` `serde_as` helper to make sure fields are serialized deterministically.

feat: more derives for conda lock

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__parsed matchspecs.snap
crates/rattler_conda_types/src/version_spec/version_tree.rs

Fixes parsing of `blas *.* mkl` and `pytorch=*=cuda*` which would both cause panics.

fix: edge cases for matchspec parsing

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/topological_sort.rs

Adds topological sorting of `PackageRecord`s from [`rattler-server`](https://github.com/mamba-org/rattler-server). This implementation differs slightly in that it allows any `Vec` of something that resembles a `PackageRecord` to be sorted. This includes `RepoDataRecord` and `PrefixRecord`.

feat: topological sort of PackageRecords

---

.github/workflows/rust-compile.yml
CHANGELOG.md
crates/rattler_shell/Cargo.toml
crates/rattler_shell/src/shell/mod.rs

Refactored the shell detection code. The following changes were made.
- Added a function to detect the current shell based on the `SHELL` environment variable.
- Added a function to detect the current shell based on the parent process name (behind a feature flag).
- Removed the `ShellEnum::detect_from_environment()` method and moved implementation into `ShellEnum::default()`.
To determine an appropriate current shell use:
```rust
let shell = ShellEnum::from_env() // First try to detect from $SHELL
.or_else(ShellEnum::from_parent_process())  // Otherwise check the parent process
.unwrap_or_default();  // Otherwise fall back to the os's default
```
Fix #216

refactor: detect current shell

---

crates/rattler_conda_types/src/platform.rs

Changed the error message for parsing platforms to also include available values:
```
'foo' is not a known platform.
```
changed to:
```
'foo' is not a known platform. Valid platforms are 'noarch', 'linux-32', 'linux-64', 'linux-aarch64', 'linux-armv6l', 'linux-armv7l', 'linux-ppc64le', 'linux-ppc64', 'linux-s390x', 'linux-riscv32', 'linux-riscv64', 'osx-64', 'osx-arm64', 'win-32', 'win-64', 'win-arm64', 'emscripten-32'
```

feat: better parse error message

---

crates/rattler_shell/src/shell/mod.rs
crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__activation_script_zsh.snap

This should fix activation for `zsh` shells (didn't find and execute any activation scripts).

zsh also uses `sh` as shell extension

---

crates/rattler/src/lib.rs
crates/rattler_conda_types/src/conda_lock/builder.rs
crates/rattler_conda_types/src/conda_lock/mod.rs
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__packages_for_platform-2.snap
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__packages_for_platform-3.snap
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__packages_for_platform.snap
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__read_conda_lock.snap
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__read_conda_lock_python.snap
crates/rattler_package_streaming/tests/extract.rs
crates/rattler_shell/src/activation.rs

So that it is possible to re-create a package record from a locked package

feat: added experimental fields to conda lock

---

crates/rattler/src/install/python.rs
crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version/parse.rs
crates/rattler_conda_types/src/version_spec/mod.rs

This PR does a complete refactor of the version implementation. The primary goal was to reduce the memory footprint because versions are used in RepoData quite a lot. The secondary goal was to simplify the implementation, I think I achieved this by returning an iterator of the version segments vs accessing multiple arrays to get to the data. The implementation of the `flag` makes it a bit more complex though. If based on a review this is the case I have some ideas.
Just like the previous implementation, this implementation tries to keep most memory on the stack unless the version requires more memory. Most versions are in the form of `1.2.3` so we can take advantage of that. The new implementation takes ~~136~~ 128 bytes of stack memory per Version. The old one was 440. Changes in heap …

refactor: version implementation

---

crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version/parse.rs

Adds the following method to `Version`:
- `Version::with_segments` extract specific segments of a version to turn `1.2a.3b.4` into for instance `2a.3b`.
- `Version::pop_segments` helper method to pop a number of segments from the back. E.g. turn `1.2.3` into `1.2`.
- `Version::strip_local` removes the local part of a version if it has it. Otherwise returns the version itself.
Fix #228

feat: add methods to manipulate a version

---

crates/rattler_conda_types/src/conda_lock/mod.rs

Fixes an issue where the channel couldn't be reconstructed from local urls (`file:///...`).

fix: issue with reconstructing channel and filename from local channel

---

crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/mod.rs

Fix #235 
The matchspec `>2.10*` doesnt make any sense and its actually a bug introduced during build if someone uses `=>2.10` instead of `>=2.10`.
Rattler previously already sorta ignored this case but the check didn include a version just ending in `*`. It does now.

fix: issue #235

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/version/mod.rs

Closes #207
Currently, `MatchSpec` and `NamelessMatchSpec` share a considerable amount of logic and fields, with the former essentially being the latter plus a name field.
A future PR should look into merging these two classes to reduce redundancy, streamline the codebase and improve maintainability.

Add support for sha256 and md5 field in matchspec

---

crates/libsolv_rs/src/conda_util.rs
crates/libsolv_rs/src/pool.rs

Reuse the previously parsed MatchSpec to eliminate re-parsing in an inner loop.
|                                    | libsolv | libsolv-rs | diff         |
|------------------------------------|---------|------------|--------------|
| python=3.9                         | 13.19ms | **8.22ms**    | -4.97ms (35%) |
| tensorboard=2.1.1, grpc-cpp=1.39.1 | 1.56s   | **1.24s**      | -0.31s (20%)  |

perf: dont parse matchspec in inner loop

---

crates/libsolv_rs/Cargo.toml
crates/libsolv_rs/src/conda_util.rs
crates/libsolv_rs/src/id.rs
crates/libsolv_rs/src/pool.rs
crates/libsolv_rs/src/problem.rs
crates/libsolv_rs/src/solver/clause.rs
crates/libsolv_rs/src/solver/mod.rs

Improve performance of the solver by caching the candidates separately from the sorted candidates. The candidates were also computed to compare different solvables.
With these improvements libsolv-rs beats the C impl in every case. (on my machine..)
|                                    | libsolv | libsolv-rs |
|------------------------------------|---------|------------|
| python=3.9                         | 13.267ms | **8.60ms**    |
| xtensor, xsimd                     | 9.7439ms | **4.15ms**    |
| tensorflow                           | 1.3159s | **0.753s**    |
| quetz                                   | 3.09s | **2.38s**    |
| tensorboard=2.1.1, grpc-cpp=1.39.1 | 1.5399s | **0.241s**    |

perf: cache candidates seperate from their sorting

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs

Make it easier to for the user to check if repodata was not found or if there was another error.

misc: add not found error to the fetch repo data errors 

---

crates/rattler_libsolv_rs/src/conda_util.rs

Issue found when trying libsolve rs in pixi

fix: allow unfound candidates and return empty vector when that happens

---

crates/rattler_shell/src/shell/mod.rs

Used so we can parse it directly from a string

feat: add from_str to the shellenum

---

crates/rattler/src/install/apple_codesign.rs
crates/rattler/src/install/link.rs
crates/rattler/src/install/mod.rs
crates/rattler/src/lib.rs
crates/rattler/src/package_cache.rs
crates/rattler/src/validation.rs
crates/rattler_macros/src/lib.rs

add documentation to all the crates

---

crates/rattler-bin/src/commands/create.rs

use `default_cache_dir` in rattler

---

.github/workflows/rust-compile.yml

Since I want to have a pixi build for aarch64, I would like to activate the build for aarch64 :)
Unfortunately, `ring` is still a dependency for rattler which makes us still unable to build this for ppc64le
```
❯ cargo tree -i ring
ring v0.16.20
├── rustls v0.21.2
│   ├── hyper-rustls v0.24.0
│   │   └── reqwest v0.11.18
│   │       ├── rattler v0.5.0 (/Users/pavel/projects/rattler/crates/rattler)
│   │       │   └── rattler-bin v0.5.0 (/Users/pavel/projects/rattler/crates/rattler-bin)
│   │       ├── rattler-bin v0.5.0 (/Users/pavel/projects/rattler/crates/rattler-bin)
│   │       ├── rattler_networking v0.5.0 (/Users/pavel/projects/rattler/crates/rattler_networking)
│   │       │   ├── rattler v0.5.0 (/Users/pavel/projects/rattler/crates/rattler) (*)
│   │       │   ├── rattler-bin …
```

Also build aarch64

---

.github/workflows/rust-compile.yml

Since the addition of aarch64 we have some CI failures. This PR is to try and fix that and simplify the whole pipeline by utilizing https://github.com/taiki-e/setup-cross-toolchain-action

fix: simplify ci

---

crates/rattler_package_streaming/src/write.rs

Archives produced from rattler-build, which under the hood use functionalities in this crate, couldn't be un-archived.
I manually proved this by persisting outputs of the `write_tar_bz2` function in one of the [tests](https://github.com/mamba-org/rattler/blob/cede9c1479fe9994c7fa03d5cca85075779a7ddf/crates/rattler_package_streaming/tests/write.rs#L163), and then manually running 
```
tar -xzvf pytweening-1.0.4-pyhd8ed1ab_0.tar-new.tar.bz2
```
which would before this change yield the following error:
```
tar: Error opening archive: Unrecognized archive format
```
This error would also appear if I were to try and install that package using mamba:
```
InvalidArchiveError('Error with archive /path/to/pytweening-1.0.4-pyhd8ed1ab_0.tar-new.tar.bz2.  You probably need to delete and re-download …
```

Fix: Generate valid tar archives

---

crates/rattler_conda_types/src/version_spec/parse.rs

Fixes: https://github.com/prefix-dev/pixi/issues/278
The issue was that our Constraint parser didn't account for local versions (e.g. `1.2.3+abc`)

fix: local version parsing in constraint

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/Cargo.toml
crates/rattler/src/install/mod.rs
crates/rattler/src/package_cache.rs
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/lib.rs
crates/rattler_networking/src/retry_policies.rs

Adds retry behavior for extracting packages. I'm not entirely sure how I can test this properly though...
This was reported in pixi: https://github.com/prefix-dev/pixi/issues/273 . I will try to test-drive it with pixi.

add retry behavior for package cache downloads

---

crates/rattler_libsolv_rs/src/problem.rs

Fix: https://github.com/prefix-dev/pixi/issues/290

fix: typo in solver error message

---

crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/match_spec/parse.rs

This is currently being exposed to be utilised in py-rattler.

Expose ParseMatchSpecError in rattler_conda_types

---

.gitignore
CONTRIBUTING.md
README.md
pixi.toml

addresses #282
ran a pixi init and added depends listed in environments.yml. 
Needing feedback on
- what versions for which packages we'll want for the pixi spec as I just did `pixi add ...`
- whether making a CONTRIBUTING.md from the primary README.md is needed
- verbiage and correctness in CONTRIBUTING.md

address issue #282

---

crates/rattler_virtual_packages/Cargo.toml
crates/rattler_virtual_packages/src/cuda.rs

Adds a new CUDA driver version detector using the nvidia-smi executable. The implementation defaults to this on musl-based targets because dynamically linked libraries are not supported there. 
Fixes https://github.com/prefix-dev/pixi/issues/294

feat: use nvidia-smi on musl targets

---

py-rattler/pixi.toml

If `PIP_REQUIRE_VIRTUALENV` is set to `true` in the user's environment, `maturin develop` fails because the `pip` subcommand doesn't recognize the env as a venv.
This works around that.

fix: workaround for `PIP_REQUIRE_VIRTUALENV` env variable

---

crates/rattler/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/conda_lock/builder.rs
crates/rattler_conda_types/src/conda_lock/mod.rs
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__read_conda_lock.snap
crates/rattler_conda_types/src/conda_lock/snapshots/rattler_conda_types__conda_lock__test__read_conda_lock_python.snap
crates/rattler_digest/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
py-rattler/Cargo.lock

This PR replaces some of the HashMaps in the conda-lock data structures with `IndexMap` (keeps order of insertion) and `BTreeMap` (sorts by key). This ensures that we get a consistent output in pixi.
I used `IndexMap` in the places where I thought the order of the source elements was important. For instance, the dependencies specified in the repodata.
I used `BTreeMap` where I think the order doesn't matter but it should be consistent.

fix: ensure consistent sorting of locked packages

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version_spec/mod.rs

While working on this issue:
- https://github.com/prefix-dev/pixi/issues/76
I realized that I was going to need to be able to deserialize the `NamelessMatchSpec` struct from a mapping. I believe the easiest way to allow this is by adding `Deserialize` to `derive` in the correct places.
On `NamelessMatchSpec` I also chose to use `DisplayFromStr` for `version` and `build` because I believe that's the easiest way to do it. I would be happy to change it if that's not right though.
Below is my simplified use case:
```rust
use std::fs;
use std::path::PathBuf;
use indexmap::IndexMap;
use clap::{Parser};
use serde::Deserialize;
use serde_with::{serde_as, DisplayFromStr, PickFirst};
use rattler_conda_types::NamelessMatchSpec;
#[derive(Parser)]
#[command(name = "tt - TOML test")]
#[command(author = …
```

Updates to `NamelessMatchSpec` to allow deserializing

---

crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/platform.rs
py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/pyproject.toml
py-rattler/rattler/platform/__init__.py
py-rattler/rattler/platform/platform.py
py-rattler/rattler/shell/__init__.py
py-rattler/rattler/shell/shell.py
py-rattler/src/error.rs
py-rattler/src/lib.rs
py-rattler/src/platform.rs
py-rattler/src/shell.rs

Some recreational coding to explore how we can make nice Python bindings for rattler.
The biggest challenge is the enum for Platform (and other options).

Start wrapping everything necessary for shell activation for py-rattler

---

crates/rattler_libsolv_rs/src/lib.rs
crates/rattler_libsolv_rs/src/pool.rs
crates/rattler_libsolv_rs/src/problem.rs
crates/rattler_libsolv_rs/src/solver/clause.rs
crates/rattler_libsolv_rs/src/solver/mod.rs

Adds the generic package name all over the place where this wasn't the case yet.

fix: add N generic everywhere

---

crates/rattler_libsolv_rs/src/id.rs
crates/rattler_libsolv_rs/src/lib.rs
crates/rattler_libsolv_rs/src/pool.rs
crates/rattler_libsolv_rs/src/solvable.rs
crates/rattler_libsolv_rs/src/solver/mod.rs
crates/rattler_solve/src/libsolv_rs/input.rs
crates/rattler_solve/src/libsolv_rs/mod.rs

This removes the notion of "repo" from the solver. This information was not used at all and can now be stored inside the generic parameters if you need it.

refactor: remove repo from pool

---

crates/rattler_solve/src/libsolv_rs/input.rs

Fixes two issues:
1. Solvables were added in a non-deterministic fashion which causes non-determinism in errors.
2. The IDs of the solvables were not returned which caused an issue that installed packages were not detected.

fix: non-determinism error

---

crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_repodata_gateway/src/sparse/mod.rs
test-data/channels/dummy/linux-64/repodata.json

Implements the changes discussed in https://github.com/conda-incubator/ceps/pull/61 . 
This shouldn't really affect anyone just yet since there are no server implementations of repodata version 2 yet.

feat: implement base_url cep

---

crates/rattler_conda_types/src/generic_virtual_package.rs
crates/rattler_libsolv_rs/src/lib.rs
crates/rattler_libsolv_rs/src/problem.rs
crates/rattler_libsolv_rs/src/solver/mod.rs
crates/rattler_libsolv_rs/src/solver/snapshots/rattler_libsolv_rs__solver__test__resolve_with_conflict.snap
crates/rattler_solve/Cargo.toml
crates/rattler_solve/src/libsolv_rs/mod.rs

Removal of `VersionTrait` and lets the implementer decide how to format multiple solvables in the error function.

feat: display merged candidates

---

.github/workflows/check-lfs.yml
.github/workflows/rust-compile.yml

Added job to test if everything stayts an LFS pointer.

test: added job to check for lfs links

---

crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs

Bump json-patch to include https://github.com/idubrov/json-patch/pull/28. This fixes an issue where an unrecoverable stack overflow could occur when applying jlap patches.

bump: json-patch 1.1.0

---

crates/rattler_libsolv_rs/src/mapping.rs
crates/rattler_libsolv_rs/src/solver/mod.rs
crates/rattler_libsolv_rs/src/solver/watch_map.rs

Refactored the `Mapping` class so that it allows random insertion, and can be used when the number of elements is not yet known.
Should speed up the current `watch_map`.

Refactor `Mapping`

---

crates/rattler_conda_types/src/platform.rs

Rust is also thinking like this: https://github.com/rust-lang/rust/blob/e437e57954ee1d1cd4630d222e42ad0277cd4bf2/library/std/src/sys/unix/env.rs#L177-L186
(and not for WASI).

emscripten is a unix variant

---

crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs

removed pub and pub(crate) on Constraint, it's
parsing and implemented From<Constraint> for
VersionSpec
Revert "expose other cargo commands"
This reverts commit 9a22ec9966b3ad679e1d54af773f23e179725eef.

hide implementation detail, version_spec::Constraint

---

crates/rattler_libsolv_rs/Cargo.toml
crates/rattler_libsolv_rs/src/id.rs
crates/rattler_libsolv_rs/src/problem.rs
crates/rattler_libsolv_rs/src/solvable.rs
crates/rattler_libsolv_rs/src/solver/clause.rs
crates/rattler_libsolv_rs/src/solver/mod.rs
crates/rattler_libsolv_rs/src/solver/snapshots/rattler_libsolv_rs__solver__test__missing_dep.snap
crates/rattler_libsolv_rs/src/solver/snapshots/rattler_libsolv_rs__solver__test__no_backtracking.snap
crates/rattler_libsolv_rs/src/solver/snapshots/rattler_libsolv_rs__solver__test__unsat_constrains_2.snap

Adds some formatting improvements for solvables and out logging.
Also adds:
- Additional tests
- Reformats some of the insta tests to make them more clear (e.g. `9` becomes `foo=9`).

refactor: improve formatting

---

crates/rattler_solve/src/resolvo/mod.rs

I've found a typo in `rattler_solve/src/resolvo/mod.rs` which stated that `this` solver is implemented using the `libsolv` library. 
I think the correct word should be `resolvo` because we implement it for `resolvo` and we do it under `src/resolvo`.

Change solver implementation doc comment

---

py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/pixi.lock
py-rattler/pixi.toml
py-rattler/rattler/__init__.py
py-rattler/rattler/channel/channel.py
py-rattler/rattler/solver/__init__.py
py-rattler/rattler/solver/solver.py
py-rattler/src/error.rs
py-rattler/src/lib.rs
py-rattler/src/match_spec.rs
py-rattler/src/repo_data/sparse.rs
py-rattler/src/solver.rs
py-rattler/tests/unit/test_solver.py

This PR achieves functionality described in #353
TODO:

feat: add solver

---

crates/rattler_networking/src/authentication_storage/storage.rs

closes #363 
This reduces the way the message used to scream at you, while it is totally normal to not have a keyring on your system. 
Still not the best as it might be better to give this warning only once but this should help.

misc: simplify code and change warning to debug

---

crates/rattler/src/install/mod.rs
crates/rattler/src/install/transaction.rs
py-rattler/rattler/__init__.py
py-rattler/rattler/linker/__init__.py
py-rattler/rattler/linker/linker.py
py-rattler/src/error.rs
py-rattler/src/lib.rs
py-rattler/src/linker.rs
py-rattler/src/prefix_record.rs
py-rattler/src/repo_data/repo_data_record.rs
py-rattler/tests/unit/test_link.py
py-rattler/tests/unit/test_solver.py

This PR adds a `link` function to create an environment for solved dependencies. 
Closes #354

Add `link` function to py-rattler

---

crates/rattler_shell/src/activation.rs
crates/rattler_shell/src/shell/mod.rs
py-rattler/src/shell.rs

There is one more fix I need to do.
Closes #306

Nushell fixes

---

crates/rattler_conda_types/src/package/has_prefix.rs

Removes the hardcoded `/opt/anaconda1anaconda2anaconda3` string from the binary and instead constructs it at runtime. This is required to ensure that when using the rattler binary in recipe the string is not replaced.

fix: construct placeholder string at runtime

---

crates/rattler_repodata_gateway/src/fetch/cache/mod.rs
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs

Conda has been using `.info.json` for a few releases now.
My edits to the draft CEP are expressed in https://github.com/conda-incubator/ceps/pull/48/files
I noticed rattler is back to using `.lock` files copied from what cargo does, instead of the (has plenty of its own problems) record locking found in mamba.

match conda with `.state.json` -> `.info.json`

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_repodata_gateway/src/sparse/mod.rs
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/tests/backends.rs
py-rattler/Cargo.lock
py-rattler/rattler/repo_data/sparse.py
py-rattler/rattler/solver/solver.py
py-rattler/src/repo_data/sparse.rs
py-rattler/src/solver.rs
test-data/channels/pytorch/linux-64/repodata.json

Skips options for a package in other channels if it is already found in channels that are defined first.

feat: add strict channel priority option

---

crates/rattler_conda_types/src/match_spec/mod.rs

This will fix the `MatchSpec` not being found in the jetbrains ide

fix: avoid use of \ in doctest strings, for ide integration

---

crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/serde.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__read_conda_lock.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__read_conda_lock_python.snap
test-data/conda-lock/forward-compatible-lock.yml

Adds an error when parsing a lockfile with a version higher than the currently supported version. 
Should make https://github.com/prefix-dev/pixi/issues/424 more clear.

feat: add forward compatibility error

---

crates/rattler_digest/src/lib.rs
crates/rattler_repodata_gateway/src/fetch/cache/mod.rs
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs

Fixes an issue where the client-side hash was used to determine the required server-side patches. This will fail in a lot of cases because the data is not actually bit-for-bit the same. JLAP actually stores the server-side hash seperately, which is not what this code does as well. I also refactored the code a bit to remove whitespaces in the repodata file which saves a significant amount of space.

fix: jlap wrong hash

---

crates/rattler_shell/src/shell/mod.rs

Closes https://github.com/prefix-dev/pixi/issues/437
The activation runs a this `openssl_activate.bat` when building the environment:
```batch
@echo off
if "%SSL_CERT_FILE%"=="" (
set SSL_CERT_FILE=%CONDA_PREFIX%\Library\ssl\cacert.pem
set __CONDA_OPENSLL_CERT_FILE_SET="1"
)
```
Which results in the following result when we call the `env` in cmdexe:
```
__CONDA_OPENSLL_CERT_FILE_SET="1"
```
This seems to be the only shell that does it that way. But our parser just keeps those `"` around which breaks because we add them again in our powershell `fn set_env_var` 
This PR strips the `"`.

fix: environment activation for windows

---

crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_solve/src/resolvo/mod.rs

This should really help make installation more correct. 
I got the issue that `conda-forge::python` and `conda::python` got the same result after installation. 
So I changed the type of the channel to be a channel from the start. 
WDYT?

refactor: make the channel in the matchspec struct an actual channel

---

crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/lib.rs
crates/rattler_networking/src/redaction.rs
crates/rattler_package_streaming/src/lib.rs
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs

This PR adds redaction of tokens in URLs used by errors. I may have missed a few locations, but I think I got them all..

fix: redact tokens from urls in errors

---

crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/match_spec/matcher.rs

I could've used this error in `rattler-build`.

expose `StringMatcherParseError`

---

crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/patches.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__patches__test__patch_purl.snap
crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/conda.rs
crates/rattler_solve/tests/backends.rs
test-data/channels/patch/linux-64/patch_instructions_4.json

Implementation of https://github.com/conda-incubator/ceps/pull/63

feat: add purls to PackageRecord and lockfile

---

crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/pypi.rs
crates/rattler_lock/src/serde.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__read_conda_lock.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__read_conda_lock_python.snap

This renames `pip` to `pypi` in lock files. `pip` is actually the installer and we don't really use that. When we talk about pip packages we usually mean pypi packages.
Since this is a forward-incompatible change I bumped the lock-file version to 3.

refactor: rename pip to pypi in lock

---

crates/rattler_virtual_packages/src/cuda.rs

Remove `compile_error` and simply use an empty list where appropriate. 
Although Cuda won't be detected on Android it also wont fail to compile.
See #417

fix: allow compilation of android target

---

CHANGELOG.md
crates/rattler_repodata_gateway/src/fetch/mod.rs

We want to try `rattler` and `rattler-build` within the client infrastructure. This client uses JFrog Artifactory to proxy conda repositories. The deployed version has a bug where the `repodata.json.zst` is cached indefinitely. An option to disable support for bz2 and zstd would allow us to use rattler with this version.

add options to disable zstd and bz2

---

crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/authentication_storage/fallback_storage.rs
crates/rattler_networking/src/lib.rs

The tests for the authentication storage randomly failed. I think this was caused by multiple threads writing to the fallback storage at the same time. This was only guarded by a mutex but multiple objects referring to the same file could exists. I replaced the mutex with a filelock to ensure that the multiple threads (and processes) are synchronized.
By request I also changed the logging behavior to ensure that the warning about fallback storage is only printed once (per file).

fix: use filelock for authentication fallback storage 

---

crates/rattler_conda_types/src/match_spec/matcher.rs
crates/rattler_conda_types/src/match_spec/parse.rs

Attempt to add some tests for ParseMatchSpecError, ParseMatchSpecError and extra test case for matching special characters: https://github.com/mamba-org/rattler/issues/205

Add ParseMatchSpecError and ParseMatchSpecError tests

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_networking/src/authentication_storage/backends/file.rs
crates/rattler_networking/src/authentication_storage/backends/keyring.rs
crates/rattler_networking/src/authentication_storage/backends/mod.rs
crates/rattler_networking/src/authentication_storage/mod.rs
crates/rattler_networking/src/authentication_storage/storage.rs
crates/rattler_networking/src/lib.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs

When running within a CI, it is sometimes easier not to rely on the native authentication toolchain, but to use a simple credentials file instead (see https://github.com/prefix-dev/rattler-build/issues/334). This PR adds an option to force the use of this fallback file and disable the use of the system toolchain.

add option to force usage of fallback_auth_store

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__deserialize_no_packages_conda.snap
crates/rattler_repodata_gateway/src/sparse/mod.rs
test-data/channels/dummy-no-conda-packages/linux-64/repodata.json

I am using rattler in a context that has to deal with _really_ old repodata.json files that don't have the "packages.conda" field and thus they fail with this error message:
```
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("missing field `packages.conda`", line: 205, column: 1) }
```
I recognize that packages.conda has been created by conda build/index for years now, but this means rattler isn't backwards compatible with the (very) old state of repodatas and it is not trivial to upgrade the repodatas that I am dealing with. Without this, I will be potentially blocked from using rattler in important contexts. Rattler would still produce this field as an empty map by default, and it would default to an empty map when it's missing from a repodata.json …

Default value for conda_packages in repodata.json

---

crates/rattler_networking/src/authentication_storage/storage.rs
crates/rattler_networking/src/lib.rs

While testing the `auth-file` feature for `rattler-build` (https://github.com/prefix-dev/rattler-build/pull/413) I noticed that the wildcard extension for domains does not work correctly:
`https://repo.prefix.dev` was matched with `repo.prefix.dev` and `*.repo.prefix.dev`, but not with `*.prefix.dev`. On closer inspection, it looks like the function never worked properly: See https://github.com/mamba-org/rattler/pull/252
This PR fixes the wildcard handling and adds a unit test for it.

fix wildcard expansion for stored credentials of domains

---

.github/workflows/release-python.yml

Fixes:
- pip error on some targets while testing wheel
Removes:
- removes rustls wheel compilation targets:
- s390x-unknown-linux-gnu
- powerpc64le-unknown-linux-gnu
- powerpc64-unknown-linux-gnu

ci: fix python release

---

crates/rattler_repodata_gateway/src/fetch/mod.rs

Fixes https://github.com/prefix-dev/pixi/issues/434
as a bonus, `ValidatedCacheState` now has `Debug`

fix: re-download the repodata cache if is out of sync/corrupt

---

crates/rattler_conda_types/src/package_name.rs

Adds a `Borrow<str>` implementation for `PackageName`.
This allows indexing `HashMap`s with a `PackageName` as key with a `str`. e.g.:
```rust
fn get_package_version(map: &HashMap<PackageName, Version>) -> Option<&Version> {
maps.get("normalized_package_name")
}
```
just works.
Previously you would have to write:
```rust
fn get_package_version(map: &HashMap<PackageName, Version>) -> Option<&Version> {
maps.get(PackageName::from_str("normalized_package_name").unwrap())
}
```
Similar to https://github.com/prefix-dev/rip/pull/89

feat: allow using `str` in `HashMap`s with a `PackageName` key

---

crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/write.rs
crates/rattler_package_streaming/tests/write.rs

This PR improves the zstd compression by:
- enabling multithreading for compression (closes #133)
- sets the size of the archive which affects compression effectiveness
- see [`set_pledged_src_size`](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.set_pledged_src_size)
- see <https://github.com/conda/conda-package-streaming/issues/57>

feat: improve zstd compression

---

crates/rattler_conda_types/benches/parse.rs
crates/rattler_conda_types/src/package/paths.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/version/bump.rs
crates/rattler_index/tests/test_index.rs
crates/rattler_lock/src/lib.rs
crates/rattler_package_streaming/tests/write.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs
crates/rattler_repodata_gateway/src/utils/flock.rs
crates/rattler_shell/src/activation.rs
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/src/libsolv_c/input.rs
crates/rattler_virtual_packages/src/libc.rs
crates/rattler_virtual_packages/src/osx.rs

automatic clippy fixes

---

crates/rattler/src/install/mod.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_digest/src/lib.rs
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/seek.rs
crates/rattler_package_streaming/tests/extract.rs
crates/rattler_repodata_gateway/src/fetch/cache/mod.rs
crates/rattler_repodata_gateway/src/utils/simple_channel_server.rs
crates/rattler_solve/tests/backends.rs

This function allows us to extract a single `PackageFile` from a given archive.

Add `read_package_file` function

---

crates/rattler/src/install/link.rs

When reflinking is not supported by the filesystem users would be spammed with error logs. I've reduced their level to `debug` now.

fix: reduce tracing level for reflink

---

crates/rattler_package_streaming/src/write.rs

@orhun maybe you can review this one

allow the full range of compression levels for zstd

---

crates/rattler_package_streaming/src/write.rs

needed to store them as "normalized" numbers in the rendered recipe in rattler-build.

feat: make compression conversion functions `pub`

---

crates/rattler_solve/src/resolvo/mod.rs

When building pixi, I got the warning:
```
warning: using `.deref()` on a double reference, which returns `&RepoDataRecord` instead of dereferencing the inner type
--> /Users/wolfv/Programs/rattler/crates/rattler_solve/src/resolvo/mod.rs:449:61
|
449 |                 SolverPackageRecord::Record(rec) => Some(rec.deref().clone()),
|                                                             ^^^^^^^^
|
= note: `#[warn(suspicious_double_ref_op)]` on by default
warning: `rattler_solve` (lib) generated 1 warning
```
I think this fixes it.

chore: fix warning for deref on a double reference

---

crates/rattler_conda_types/src/channel/mod.rs

There was no way to always get a name from the channel that is used in the `pixi` toml. Though this would be a better place.

feat: add name() to channel

---

crates/rattler/src/install/clobber_registry.rs
test-data/clobber/clobber-1-0.2.0-h4616a5c_0.tar.bz2
test-data/clobber/clobber-2-0.2.0-h4616a5c_0.tar.bz2
test-data/clobber/clobber-3-0.2.0-h4616a5c_0.tar.bz2
test-data/clobber/recipe/recipe-version-2.yaml

Also adds a few more tests for clobbering

fix: self-clobbering when updating a package

---

Cargo.toml
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/resolvo/conda_util.rs
crates/rattler_solve/src/resolvo/mod.rs
py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/build.rs

This will change to the released version when a resolvo release is done.

feat: upgrade to latest resolvo main

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/libsolv_c/mod.rs
crates/rattler_solve/src/resolvo/conda_util.rs
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
py-rattler/rattler/solver/solver.py
py-rattler/src/lib.rs
py-rattler/src/solver.rs

This could be very useful for the bots and also for `rattler-server`.

add timeout parameter and SolverOptions to return early

---

Cargo.toml
crates/rattler_solve/Cargo.toml

Bumps resolvo to 0.3.0 and removes source dependency in preperation of a new release.

bump: resolvo 0.3.0

---

py-rattler/Cargo.toml

Remove patch to use resolvo git dependency from the py-rattler crate.

chore: remove resolve git dependency

---

Cargo.toml
crates/rattler/src/package_cache.rs
crates/rattler_package_streaming/tests/write.rs
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs
crates/rattler_repodata_gateway/src/utils/simple_channel_server.rs
crates/rattler_shell/src/shell/mod.rs

- The Zip Reader now reads 3 ranges instead of two, but I didn't investigate further why that would happen ... kinda weird!
- I didn't manage to update `axum`. They removed the `axum::Server` and point to `hyper` instead. However, if I see correctly, the server in hyper is also more complicated. There is a more simple `axum::serve` that I used e.g. in `rattler-server` but idk how to deal with the graceful shutdown etc. that we are using.

chore: try to upgrade most dependencies

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/driver.rs
crates/rattler/src/install/mod.rs
crates/rattler/src/install/transaction.rs
crates/rattler/src/install/unlink.rs
py-rattler/Cargo.lock
py-rattler/src/linker.rs

We observed a race condition when removing empty folders - during the execution of a transaction it can happen that one package gets unlinked and cleans up empty folders after itself, while another one is already installing new files into the folders. This is a race condition due to the way we parellely link all the files. 
In order to fix this issue this PR moves the cleaning out of empty folders until after we're done unlinking and linking new files into the prefix and then does a (synchronous) cleaning of all empty folders in the prefix (that are not explicitly mentioned as empty directories).

fix: remove drop-bomb, move empty folder removal to `post_process`

---

crates/rattler/Cargo.toml
crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/driver.rs
crates/rattler/src/install/link.rs
crates/rattler/src/install/mod.rs
crates/rattler/src/install/python.rs
test-data/clobber/clobber-pynoarch-1-0.1.0-pyh4616a5c_0.tar.bz2
test-data/clobber/clobber-pynoarch-2-0.1.0-pyh4616a5c_0.tar.bz2
test-data/clobber/recipe/recipe-noarch.yaml

I hit a bug where the `unclobber` function tried to run `fs::rename` on non-existing files (because these files came from `noarch: python` packages where the final path got renamed from `site-packages/bla.py` to `lib/pythonX.X/site-packages/bla.py`).
This fix is relatively ugly (because we compute the "final" name for the file multiple times and entry points are also not properly handled yet.
Maybe we should discuss real quick how we want to handle entry points (entry points don't need to strictly be linked into the env since we can recreate them when we need to).

fix: keep in mind python: noarch packages in clobber calculations

---

crates/rattler_index/src/lib.rs
crates/rattler_index/tests/test_index.rs

The produced repodata.json from `rattler_index` would put all the packages, regardless of the file format, into the `packages.conda` section of the repodata.json
TarBz2 packages now go to the `packages` section, while Conda packages still go to `packages.conda`. I've added a test case to validate the desired behaviour.

Fix: Add indexed packages to the relevant section in the repodata

---

crates/rattler_conda_types/src/platform.rs

This makes it more backward compatible (used in `rattler-build`) and makes us emit an `index.json` file that looks more like the one from `conda-build`.
ref: https://github.com/prefix-dev/rattler-build/issues/593
ref: https://github.com/prefix-dev/rattler-build/issues/444
I also started a discussion in the conda build gitter thing.

Fix arch for osx-arm64 and win-arm64

---

.github/workflows/lint-pr.yml
.github/workflows/python-bindings.yml

Adds a workflow to lint PR titles to ensure that they follow conventional commit.

chore(ci): add workflow to lint pr title

---

crates/rattler/src/package_cache.rs
crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/read.rs
crates/rattler_package_streaming/tests/extract.rs

This adds a test to check that the flaky download behavior has been fixed. This was caused by a Read implementation to consistently return an error at some point which caused the zip crate to panic.

fix: flaky package extract error

---

Cargo.toml
crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_index/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_shell/Cargo.toml
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/Cargo.toml
py-rattler/.gitignore

Releaze-pls seems to bump all packages if their dependencies are defined in the workspace. This PR reverts that change and instead makes every crate depend on other crates in the same workspace via local references.

fix: dont use workspace dependencies for local crates

---

crates/rattler_repodata_gateway/src/sparse/mod.rs
crates/rattler_solve/src/resolvo/conda_util.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_solve/tests/snapshots/backends__libsolv_c__solve_python_numpy.snap
crates/rattler_solve/tests/snapshots/backends__resolvo__solve_python_numpy.snap
test-data/channels/conda-forge/linux-64/repodata.json

We use track features to de-prioritize packages.
Sometimes, the solver is forced to select a given package, e.g. when selecting `numpy-XY-<hash>` it might have a dependency on `pypy`. Numpy variants themselves are not down-prioritized, though.
If we detect that a package forces only dependencies that have track features (such as the case for the numpy variant that only works together with `pypy`) we also "inherit" the down-weighing to `numpy` (otherwise the solver would be forced to use pypy later on).
We already had the code for this but it was missing a `!` – this PR corrects that.

fix: correct condition to downweigh track-feature packages

---

crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs
crates/rattler_conda_types/src/version_spec/version_tree.rs

This adds support to parse some nonsensical glob version constraints like `>=*` or `=*` or `<=*`. They all simply map to `*`.
Fix: https://github.com/prefix-dev/pixi/issues/669

fix: patch unsupported glob operators

---

Cargo.toml
crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_digest/Cargo.toml
crates/rattler_index/Cargo.toml
crates/rattler_libsolv_c/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_macros/Cargo.toml
crates/rattler_networking/Cargo.toml
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_shell/Cargo.toml
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/Cargo.toml

Previously we were using `version.workspace = true` for every crate. This meant that every crate would have the same version. However, we want every version to be able to have its own version. This PR changes the version behavior.

chore: every crate should have its own version

---

crates/rattler_shell/src/activation.rs
crates/rattler_shell/src/shell/mod.rs

Adds a function to force a shell to handle utf8 encoding. An implementation is provided for cmdexe through the use of the `chcp 65001` command and something similar for Powershell.
This should fix the issue encountered here https://github.com/prefix-dev/pixi/issues/930

fix: better handle utf8 paths in CmdExe and Powershell

---

crates/rattler-bin/Cargo.toml
crates/rattler/CHANGELOG.md
crates/rattler/Cargo.toml
crates/rattler_conda_types/CHANGELOG.md
crates/rattler_conda_types/Cargo.toml
crates/rattler_index/CHANGELOG.md
crates/rattler_index/Cargo.toml
crates/rattler_lock/CHANGELOG.md
crates/rattler_lock/Cargo.toml
crates/rattler_package_streaming/CHANGELOG.md
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/CHANGELOG.md
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_shell/CHANGELOG.md
crates/rattler_shell/Cargo.toml
crates/rattler_solve/CHANGELOG.md
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/CHANGELOG.md
crates/rattler_virtual_packages/Cargo.toml

* `rattler`: 0.19.1 -> 0.19.2 (✓ API compatible changes)
* `rattler_conda_types`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
* `rattler_package_streaming`: 0.19.1 -> 0.19.2 (✓ API compatible changes)
* `rattler_lock`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
* `rattler_repodata_gateway`: 0.19.1 -> 0.19.2 (✓ API compatible changes)
* `rattler_solve`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
* `rattler_shell`: 0.19.1 -> 0.19.2 (✓ API compatible changes)
* `rattler_virtual_packages`: 0.19.1 -> 0.19.2
* `rattler_index`: 0.19.1 -> 0.19.2
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- update Cargo.toml dependencies
</blockquote>
<blockquote>
- chrono deprecation warnings ([#558](https://github.com/mamba-org/rattler/pull/558))
</blockquote>
<blockquote>
- update …

chore: release

---

README.md

Adds this badge: [![Pixi Badge](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/prefix-dev/pixi/main/assets/badge/v0.json)](https://pixi.sh)

chore: add pixi badge

---

crates/rattler/src/install/link.rs

The `pkg-config` package encodes (in the binary) a "PATH" variable that looks something like:
```
/prefix_placeholder/lib:/prefix_placeholder/etc/share\0
```
So far we only replaced the initial prefix placeholder, and skipped past the rest. 
With this change we first get the whole "c-string" (until the `\0`), and then replace each occurence of the prefix in the c-string. The padding is then added to make sure that the strings are of the same length.

fix: multi-prefix replacement in binary files

---

crates/rattler_networking/src/authentication_middleware.rs
crates/rattler_networking/src/authentication_storage/backends/file.rs

We've seen issues in pixi where downloading becomes really slow because the `~/.rattler/auth.json` file is on a network file system. 
We also wanted to give better error messages if we cannot parse the JSON file.
With this change, we cache the authentication information for the lifetime of the middleware. I think this should fix the two issues mentioned above.

fix: implement cache for authentication filestorage backend

---

crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/parse.rs

fix: allow not starts with in strict mode

---

crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/pypi.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__path-based-lock.yml.snap
py-rattler/Cargo.lock
py-rattler/rattler/lock/pypi.py
py-rattler/src/lock/mod.rs
test-data/conda-lock/v4/path-based-lock.yml

Adds the `editable` field to pypi packages to indicate they are installed in editable mode.

feat: editable pypi packages

---

crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/match_spec/parse.rs

* Adds a simple way to go from a Channel to a name and back using a `ChannelConfig`.
* Parses `conda-forge::foo` as not having a namespace.

fix: matchspec empty namespace and channel cannonical name

---

Cargo.toml
crates/rattler-bin/src/commands/mod.rs
crates/rattler-bin/src/commands/virtual_packages.rs
crates/rattler-bin/src/main.rs
crates/rattler_virtual_packages/Cargo.toml
crates/rattler_virtual_packages/src/lib.rs

Implements proper archspec detection using https://github.com/prefix-dev/archspec-rs which is a port of https://github.com/archspec/archspec used by `conda`. This opens the doors to build and use architecture specific packages.
We loose the `__archspec` virtual package for wasm targets because the archspec standard does not describe these targets.
I set the default archspec for `osx-arm64` to `m1` because I think thats greatest common denominator for arm based chips on mac.
I also added a subcommand to rattler-bin to print the detected virtual packages.
On my windows machine:
```
> cargo run -- virtual-packages
__win=0=0
__cuda=12.3=0
__archspec=1=skylake
```
Under WSL:
```
> cargo run -- virtual-packages
__unix=0=0
__linux=5.15.146.1=0
__glibc=2.35=0
__cuda=12.3=0
__archspec=1=skylake …
```

feat: proper archspec detection using archspec-rs

---

crates/rattler/src/install/link.rs

There is only one form of binary replacement on Windows, and that's for "pyzzer" entrypoints. I don't think they are widely used though.
I think this might fix the issue described in https://github.com/prefix-dev/pixi/issues/1096

fix: do not do cstring replacement on windows

---

crates/rattler/src/install/link.rs
crates/rattler/src/install/snapshots/rattler__install__link__test__replace_long_prefix_in_text_file.snap
test-data/shebang_test.txt

Note: I should test the whole replace function as well

fix: replace long shebangs with `/usr/bin/env`

---

Cargo.toml
crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/authentication_middleware.rs
crates/rattler_networking/src/mirror_middleware.rs
crates/rattler_networking/src/oci_middleware.rs
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/utils/mod.rs
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/Cargo.toml
py-rattler/Cargo.lock
py-rattler/Cargo.toml

Bumping everything _except_ for `pep440_rs`. @tdejager do you know what we should do with this regarding the UV integration? Is it time to bump it?

chore: update dependencies incl. reqwest

---

crates/rattler/src/install/entry_point.rs
crates/rattler/src/install/mod.rs

We should also fix the win-arm64 launcher and maybe use the `uv` trampoline?

fix: use correct platform to decide the windows launcher

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/entry_point.rs
crates/rattler/src/install/snapshots/rattler__install__entry_point__test__windows.snap

This is a different fix from using the `uv` trampolines but fixes the immediate issue of spaces in prefix paths not working on Windows entrypoints.

fix: no shebang on windows to make spaces in prefix work

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/lib.rs
crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_repodata_gateway/src/sparse/mod.rs
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/tests/backends.rs
py-rattler/rattler/channel/channel_config.py
py-rattler/src/channel/mod.rs

This would be useful for making sure that channels are resolved relative to the `pixi.toml` file (and not the current working directory). It also makes the call to current work dir the responsibility of the user and they can catch errors (e.g. the current wrok dir is not available in wasm32 and maybe some other embedded systems or so).
I am not sure about the name though. Happy about suggestions :)

feat: make root dir configurable in channel config

---

crates/rattler/src/install/entry_point.rs
crates/rattler/src/install/link.rs
crates/rattler/src/install/mod.rs
crates/rattler_conda_types/src/prefix_record.rs
crates/rattler_conda_types/src/snapshots/rattler_conda_types__prefix_record__test__tk-8_6_12-h8ffe710_0_json.snap

This is a prerequisite for #613. Currently, records in conda-meta contain prefix placeholder metadata. This isn't currently being extracted in `PathsEntry`.
This PR extracts the placeholder information so `PathsEntry` now contains exactly what's in the records in conda-meta.

feat: add support for extracting prefix placeholder data to PathsEntry

---

Cargo.toml
crates/rattler/src/install/link.rs
crates/rattler/src/install/unlink.rs
crates/rattler_lock/Cargo.toml
crates/rattler_lock/src/url_or_path.rs
crates/rattler_shell/src/activation.rs
py-rattler/Cargo.lock

This is a more general fix for https://github.com/prefix-dev/pixi/pull/1224 .
The basic idea is that you can "canonicalize" a `UrlOrPath`. If the stored Url represents an absolute path, it is converted into a path instead. This is not completely trivial because the `Url::to_file_path` method behaves differently depending on the architecture. I had to reimplement this method.
When checking the equality of two `UrlOrPath`s they are first canonicalized so that comparing a `file:///...` and a `/..` url and path works properly. 
`UrlOrPath`s are not canonicalized before serialization, this ensures that loading a lock file and saving it again will result in the same lock file. However, when _creating_ a lock file I think it makes sense to canonicalize any instance you create.

fix: compare `UrlOrPath`

---

.github/workflows/release-python.yml
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/lib.rs
py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/pixi.toml
py-rattler/pyproject.toml

Removed the version from pixi.toml as well because I dont think it serves a purpose.

chore: bump py-rattler 0.5.0

---

crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/sparse/mod.rs

~This is a breaking change, because it introduces a lifetime parameter for `SparseRepoData`. If that's undesirable, maybe we could create an inner type (e.g. `SparseRepoData2`) wrapped by two outer types (e.g. `MemmappedSparseRepoData` and `ByteSliceSparseRepoData`).~ We ended up using `Bytes` with a self-referential borrow to get rid of the lifetime entirely, so now the change is no longer breaking 🎉.
I also took the liberty to switch from stable to unstable sorting, which has better performance characteristics. If you'd rather leave things as they are now, I can drop the commit.
Fixes #619

feat: create SparseRepoData from byte slices

---

py-rattler/rattler/prefix/prefix_paths.py

We were missing `@property` for `sha256` and `sha256_in_prefix` for `PrefixPathsEntry`.

feat: Add missing @property to sha256, sha256_in_prefix in `PrefixPathsEntry`

---

crates/rattler_lock/Cargo.toml
crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/file_format_version.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/parse/deserialize.rs
crates/rattler_lock/src/parse/mod.rs
crates/rattler_lock/src/parse/serialize.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/pypi_indexes.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__numpy-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__pypi-matplotlib-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__python-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v3__robostack-turtlesim-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__numpy-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__path-based-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__pypi-matplotlib-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__python-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__turtlesim-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v5__flat-index-lock.yml.snap
test-data/conda-lock/v5/flat-index-lock.yml

This bumps the lock-file version to `5` because starting from version `5` the pypi indexes are required if there are pypi indices. This ensures that old lock-files are still valid without the indexes but new lock-files should be considered invalid if they dont contain the indexes.

feat: adds pypi indexes to the lock-file

---

crates/rattler_conda_types/src/no_arch_type.rs
py-rattler/rattler/package/no_arch_type.py
py-rattler/rattler/repo_data/package_record.py
py-rattler/src/lib.rs
py-rattler/src/no_arch_type.rs
py-rattler/src/record.rs
py-rattler/tests/unit/test_prefix_record.py

Closes https://github.com/mamba-org/rattler/issues/630
I barely know what I'm doing so please feel free to suggest a different API or even commit directly to my branch :) Thanks!

feat: expose `*Record.noarch` in Python bindings

---

crates/rattler/src/install/link.rs

Sometimes linking was failing because we tried to compute the SHA hash of a symlink-file. When computing the hash, we follow the symlink. But since we are symlinking everything at once, and in parallel, the symlinked file is sometimes not yet there.
In that case, the SHA hash computation was failing. 
With this PR, we change it so that we always store `000...000` for symlinks.
Conda and mamba 'wait' for the files to be ready and then compute (or find) the hash. We could also do that, but on the other hand the "sha" hash of a symlink doesn't make that much sense anyways. 
Thoughts?
ref. https://github.com/prefix-dev/pixi/issues/1309

fix: sha computation of symlinks was failing sometimes

---

Cargo.toml
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/authentication_middleware.rs
crates/rattler_networking/src/authentication_storage/storage.rs

The environment variable `RATTLER_AUTH_FILE` is currently used by both `pixi` and `rattler-build` to specify an alternative storage location for the `credentials.json` file, which is crucial for authenticating to remote repositories. This feature is particularly valuable in CI or managed environments, where authentication is managed externally and credentials are stored at ephemeral paths.
Currently, both tools handle the `RATTLER_AUTH_FILE` independently, each tool implementing its own method to default to `AuthenticationStorage` when the environment variable is not set. This is evidenced in their respective codebases:
- `rattler-build` implementation: [rattler-build code](https://github.com/prefix-dev/rattler-build/blob/main/src/tool_configuration.rs#L57)
- `pixi` implementation: [pixi …

feat: respect `RATTLER_AUTH_FILE` when using AuthenticationStorage::default()

---

crates/rattler_networking/src/authentication_storage/storage.rs

When integrating https://github.com/mamba-org/rattler/pull/636 into pixi, I noticed that it is also possible to define an authentication_override_file in the global configuration and not just via `RATTLER_AUTH_FILE`. To enable code reuse, I would also like to offer a convenience function here.

feat: add AuthenticationStorage::from_file()

---

crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_repodata_gateway/src/lib.rs
py-rattler/Cargo.lock
py-rattler/rattler/repo_data/gateway.py
py-rattler/src/repo_data/gateway.rs

Adds functionality to the gateway to selectively clear the in-memory cache. This might be useful if you know the state on disk changed (like when manually reindexing).

feat: clear gateway subdirs

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/driver.rs
crates/rattler/src/install/link_script.rs
crates/rattler/src/install/mod.rs
py-rattler/src/linker.rs
test-data/link-scripts/link-scripts-0.1.0-h4616a5c_0.conda
test-data/link-scripts/recipe/pre-unlink.bat

Use semaphore in the install driver to allow sharing the semaphore with other concurrent processes. Also introduces a builder for the install driver.

refactor: use semaphore for install driver

---

crates/file_url/src/lib.rs
crates/rattler-bin/src/commands/create.rs
crates/rattler/src/cli/auth.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_networking/src/mirror_middleware.rs
crates/rattler_package_streaming/tests/extract.rs
crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_shell/src/shell/mod.rs
crates/rattler_solve/Cargo.toml
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/libsolv_c/input.rs
crates/rattler_solve/src/libsolv_c/mod.rs
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_solve/tests/snapshots/backends__resolvo__exclude_newer_error.snap
py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/pixi.toml
py-rattler/rattler/solver/solver.py
py-rattler/src/error.rs
py-rattler/src/solver.rs
py-rattler/tests/conftest.py
py-rattler/tests/unit/test_solver.py
test-data/channels/dummy/linux-64/repodata.json

Allows setting an `exclude_newer` field on `SolverTask` to exclude any record uploaded after a certain date. This is useful to make repodata from remote source more deterministic.

feat: exclude repodata records based on timestamp

---

py-rattler/Cargo.lock
py-rattler/rattler/repo_data/package_record.py
py-rattler/rattler/version/version.py
py-rattler/rattler/version/with_source.py
py-rattler/src/record.rs
py-rattler/tests/unit/test_version.py

`VersionWithSource` already existed. I refactor this to make it derive from `Version`. `PackageRecord` now returns a `VersionWithSource` for the `version` field. This will retain version string information. 
Note that comparing two `VersionWithSource` only compares the versions, not the sources.
Fixes #656

refactor: expose `VersionWithSource`

---

crates/rattler-bin/src/commands/create.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_solve/src/lib.rs
crates/rattler_solve/src/libsolv_c/mod.rs
crates/rattler_solve/src/resolvo/conda_util.rs
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
py-rattler/rattler/solver/solver.py
py-rattler/src/error.rs
py-rattler/src/solver.rs
py-rattler/tests/unit/test_solver.py
test-data/channels/dummy/linux-64/repodata.json

Implements solver strategies:
- `Highest` (default): Solve all packages to the highest compatible version.
- `LowestVersion`: Solve all packages to the lowest compatible version. This only looks at the version. This ensures that build number ordering and downprioritization remain functional.
- `LowestVersionDirect`: Solve for the lowest compatible version, similar to `LowestVersion`, but only for direct dependencies. Transitive dependencies are still sorted using the `Highest` strategy.
This is only implemented when using resolvo. When using a non-default strategy with libsolv you will get an `Unsupported` error.
This is also implemented into the binary:
```
> cargo run -- create --dry-run 'python>2' --platform linux-64 --strategy highest
+ _libgcc_mutex 0.1 conda_forge
+ libgomp 13.2.0 …
```

feat: solve strategies

---

Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/patches.rs
crates/rattler_conda_types/src/repo_data_record.rs
crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/conda.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/utils/serde/raw_conda_package_data.rs
crates/rattler_solve/src/resolvo/mod.rs
py-rattler/Cargo.lock

* Turns `purls` into a BtreeSet to ensure consistent ordering (fixes https://github.com/prefix-dev/pixi/issues/1367)
* Removed `Ord` and `PartialOrd` from `PackageRecord`. It doesnt make sense.
* Bumped `resolvo` to remove `Ord` constraint from `Version`. 
* Conversion from `CondaPackage` and `PypiPackage` to Package.
* The ability to add packages to the lock file builder from another environment.

feat: removed Ord and more

---

crates/rattler/Cargo.toml
crates/rattler/src/install/installer/indicatif.rs
py-rattler/Cargo.lock

Small fixes to the installer progress bars.
* Gray out progress bar if its not active
* Format durations better (rounded to ms)

fix: improve progress bar duration display

---

crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version_spec/mod.rs

This fixes an issue where if we check if a version a starts with b, we should ignore any trailing zero segments in b. This is because a version `1` is the same as `1.0` and `1.0.0.0.0`. So in that sense `1` starts with `1.0` as well. 
Im personally not extremely happy with this because I think its complex to understand, but this seems to be the way its implemented in conda and mamba.
Fixes #685

fix: VersionSpec starts with, with trailing zeros

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs
crates/rattler_conda_types/src/version_spec/version_tree.rs

The version spec `2023.*.*` would previously fail to parse with `RegexConstraintNotSupported`. However, in lenient parsing mode we now parse this as `2023.*`.

fix: lenient parsing of 2023.*.*

---

crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/version/mod.rs
py-rattler/rattler/install/installer.py
py-rattler/rattler/version/version.py
py-rattler/src/error.rs
py-rattler/src/version/mod.rs

This function will extend a given version to a certain length. 
If the version is already longer than the specified length, it will just return it.
For example:
```
Extending to length of 3:
1 -> 1.0.0
1.2 -> 1.2.0
1!1.2 -> 1!1.2.0
1!1.2+3.4 -> 1!1.2.0+3.4
```
This is in preparation of making the version bumping extend the version.

feat: add a function to extend version with `0s`

---

crates/rattler_conda_types/src/version/bump.rs
py-rattler/rattler/version/version.py

Previously we would fail if someone tried to bump the patch version of e.g. `1`.
Now, we extend the version in order to fulfill the request (e.g. bumping the patch version of `1` would result in `1.0.1`).

feat: when bumping, extend versions with `0` to match the bump request

---

crates/rattler_solve/Cargo.toml
crates/rattler_solve/src/lib.rs

Adds optional support for `ChannelPriority` and `SolveStrategy` to be serialized with serde.

chore: enable serialization of enums

---

crates/rattler_conda_types/src/version/bump.rs
py-rattler/Cargo.lock
py-rattler/rattler/version/version.py
py-rattler/src/version/mod.rs

I also added a `remove_local` function that removes the local segments of a version.

feat: add a `with_alpha` function that adds `0a0` to the version

---

crates/rattler_package_streaming/src/reqwest/tokio.rs

We hit a debug assert in `rattler-build` where we download files from `file:///` URLs.
Logs: https://github.com/prefix-dev/rattler-build/actions/runs/9283979823/job/25545353376
```
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/git/checkouts/rattler-c5fe433b5d5eb3e2/8eccee4/crates/rattler/src/package_cache.rs:383:14:
on_download_start was not called
stack backtrace:
0: rust_begin_unwind
at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
1: core::panicking::panic_fmt
at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
2: core::panicking::panic_display
at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:178:5
3: core::panicking::panic_str
at …
```

fix: call on_download_start also for file URLs

---

py-rattler/rattler/solver/solver.py

This PR fixes a bug where the py-rattler solver timeout did not use the entire duration of the timedelta object. 
edit: With this fix, it should work. The hack I was using to get around this bug doesn't work and so the solver thought I passed a timeout of zero.

fix: use total duration of timedelta objects

---

py-rattler/Cargo.lock
py-rattler/docs/index.md
py-rattler/examples/solve_and_install.py
py-rattler/mkdocs.yml
py-rattler/pixi.toml
py-rattler/pyproject.toml
py-rattler/rattler/install/installer.py
py-rattler/rattler/solver/solver.py

feat: update py-rattler readme

---

crates/rattler_index/src/lib.rs

We would like to use these functions for a rattler-based tool we are developing :)

chore: Make package_record_from_* functions public

---

py-rattler/Cargo.lock
py-rattler/rattler/__init__.py
py-rattler/rattler/repo_data/sparse.py
py-rattler/rattler/solver/__init__.py
py-rattler/rattler/solver/solver.py
py-rattler/src/lib.rs
py-rattler/src/solver.rs
py-rattler/tests/unit/test_solver.py

Adds back a function to use `SparseRepoData` instead of the gateway for solving: `solve_with_sparse_repodata`
Fixes #730

feat: add `solve_with_sparse_repodata`

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_solve/tests/snapshots/backends__resolvo__issue_717.snap
crates/rattler_solve/tests/snapshots/backends__resolvo__solve_with_error.snap
test-data/channels/dummy/linux-64/repodata.json

Fixes #717 
Fixes https://github.com/prefix-dev/pixi/issues/1469
This fixes parsing of `ray[default,data] >=2.9.0,<3.0.0` to fail with `InvalidPackageName` instead of `InvalidBracket`.

fix: issue 717

---

crates/rattler_repodata_gateway/Cargo.toml

Similar to #734 this adds the necessary flags to `rattler_repodata_gateway` to document the sparse and gateway features.

docs: document gateway features

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
py-rattler/rattler/install/installer.py
py-rattler/tests/unit/test_solver.py

Fixes #736 
This PR introduces strict and lenient parsing of versions in the form of `pytorch=*=*cuda` and `python ==2.7.8.*.*`.
This changes the behavior in strict mode and makes sure that `NamelessMatchSpec` and `MatchSpec` behave the same way while parsing.
In strict mode only spaces are allowed to separate the package name, version, and build string. The form `pytorch=*=*cuda` is no longer allowed and will result in an error. Instead this should be written as `pytorch * *cuda`. This removes any ambiguity about what the equality signs mean. Another form that has been removed in strict mode is the removal of the `==` sign in some specific cases like `python ==2.7`. Finally, the behavior where the version string is appended with a `*` if the version starts with a `=` is removed in strict …

fix: lenient and strict parsing of equality signs

---

crates/rattler_shell/src/activation.rs

Allows passing of custom environment variables to the activator instead of using the ones from the parent process.

feat: allow passing custom environment to run_activation

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_lock/src/utils/serde/raw_conda_package_data.rs
py-rattler/rattler/repo_data/package_record.py
py-rattler/src/record.rs

feat: return pybytes for sha256 and md5 everywhere and use md5 hash for legacy bz2 md5

---

crates/rattler_repodata_gateway/src/sparse/mod.rs

We could also be more lenient and assume a build number / build string of `0` if we only find a single `-`...
Haven't really seen that in the wild though.

feat: improve error message when parsing file name

---

.github/workflows/rust-compile.yml
crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/lib.rs
crates/rattler_cache/src/package_cache.rs
crates/rattler_package_streaming/tests/extract.rs
crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_repodata_gateway/src/utils/mod.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_virtual_packages/src/linux.rs

I've noticed that vscode showed clippy warnings.
Turned out we don't run clippy on all targets

fix: run clippy on all targets

---

crates/rattler/src/cli/auth.rs
crates/rattler_lock/src/parse/mod.rs
crates/rattler_networking/src/authentication_storage/backends/file.rs

See https://doc.rust-lang.org/std/error/trait.Error.html

fix: errors should not contain trailing punctuation

---

crates/rattler_conda_types/src/version/mod.rs
crates/rattler_conda_types/src/version/parse.rs

We copied the implicit components twice:
- once as flag on the segment
- and once as a materialized component from the SegmentIter
This should fix the double-zeros :)

fix: skip over implicit `0` components when copying

---

crates/rattler_lock/src/hash.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__numpy-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__pypi-matplotlib-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__python-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v3__robostack-turtlesim-conda-lock.yml.snap

By saving only one of those two hashes, we reduce the lock file size a bit. This should be especially noticeable in git repos, since hashes compress poorly.
This PR is a contribution to improving https://github.com/prefix-dev/pixi/issues/1509

feat: Only save md5 in lock file if no sha256 is present

---

crates/rattler_lock/src/hash.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__numpy-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__pypi-matplotlib-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__python-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v3__robostack-turtlesim-conda-lock.yml.snap

chore: revert only save md5 in lock file if no sha256 is present

---

crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_repodata_gateway/src/gateway/query.rs

Fixes #755.
The `query` method of `GatewayQuery` was not filtering records based on the provided specs. It would only filter records to be fetched when doing a recursive query.
This PR fixes that.
Note that I'm learning rust and this might not be the right way to fix this. Please let me know if I can improve this! I'd like to learn.

fix: Fix GatewayQuery.query to filter records based on provided specs

---

crates/rattler_repodata_gateway/src/gateway/mod.rs

Fixes `direct_url` tests on windows. The issue was that the packages used in the test use symlinks, which arent available by default. This PR changes to use the Windows version of `openssl` which doesnt include symlinks.

fix: direct_url query for windows

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap

I thought it was quite annoying that you cant write `python>=3.9` in strict mode. I changed the strict parser to allow package names to be followed by a version operator without a space.  `python=3.9=*` is still invalid.

fix: allow version following package in strict mode

---

Cargo.toml
crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_cache/Cargo.toml
crates/rattler_cache/src/package_cache.rs
crates/rattler_digest/Cargo.toml
crates/rattler_libsolv_c/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/retry_policies.rs
crates/rattler_repodata_gateway/Cargo.toml
py-rattler/Cargo.lock
tools/create-resolvo-snapshot/Cargo.toml

Bumps a few dependencies to reduce duplicates (especially itertools) and removes unused dependencies.

chore: bump dependencies and remove unused ones

---

Cargo.toml
crates/rattler_package_streaming/src/write.rs

Sometimes fetching packages using rattler fails with ` ZipError: "The file length is not available in the local header"`.
This error comes from the `zip` library here:
https://github.com/zip-rs/zip2/blame/b6e0a0693ba2d07f541cd9017b60df7e65817e48/src/types.rs#L688-L696 
As can be seen in a comment 
```
/* FIXME: these were previously incorrect: add testing! */
/* flags & (1 << 3) != 0 */
```
Bumping the version of zip has solved our issues and we're able to install the desired packages.

chore: bump zip to 2.1.3

---

crates/rattler_conda_types/src/package/has_prefix.rs
crates/rattler_conda_types/src/package/mod.rs

I was using rattler's `HasPrefix` to read info/has_prefix, and I couldn't unpack the `HasPrefixEntry` structs contained within, because it isn't `pub`:
```rust
let has_prefix = HasPrefix.from_str(...)?;
has_prefix.files.into_iter()
.map(|HasPrefixEntry { relative_path, file_mode, prefix }| {
// do stuff with relative_path, file_mode, and prefix
}
.collect()
```
I went thru src/package/mod.rs, and I don't think making `HasPrefixEntry` public is bad semantics. `HasPrefix` is `pub` for downstream consumption, so I think `HasPrefixEntry` should be as well? Correct me if I'm wrong, this is my first contrib to rattler :)

feat: expose `HasPrefixEntry` for public use

---

crates/rattler_conda_types/src/explicit_environment_spec.rs

Based on feedback from @baszalmstra on discord, I added a `to_path` method to the `ExplicitEnvironmentSpec` struct so that it could be dumped to file. This would be a first step in a `pixi export` PR to be submitted later. 
This is my first rust-based PR to a project (although I've fooled around with it a bit on my own), so feedback is very welcome. For testing, `ExplicitEnvironmentSpec` and `ExplicitEnvironmentEntry` didn't implement `PartialEq`, so I just unrolled the content. This isn't ideal, but I didn't want to start poking around on the main struct definitions, but I can if that's preferred.

feat: Add to_path() method to ExplicitEnvironmentSpec

---

Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/environment_yaml.rs
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__deserialize_environment_yaml@asymmetric_vqgan.environment.yaml.snap
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__deserialize_environment_yaml@channel_inversion.environment.yaml.snap
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__deserialize_environment_yaml@conda_lock_dev.environment.yaml.snap
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__deserialize_environment_yaml@mamba_dev_extra.environment.yaml.snap
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__deserialize_environment_yaml@variables.environment.yaml.snap
crates/rattler_conda_types/src/snapshots/rattler_conda_types__environment_yaml__tests__pip_section.snap
py-rattler/Cargo.lock
test-data/environments/asymmetric_vqgan.environment.yaml
test-data/environments/channel_inversion.environment.yaml
test-data/environments/conda_lock_dev.environment.yaml
test-data/environments/mamba_dev_extra.environment.yaml
test-data/environments/variables.environment.yaml

Adds a type for representing a `environment.yaml` based on https://github.com/conda/ceps/pull/81

feat: `environment.yaml` type

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap

Now allowing to parse the `NamelessMatchSpec` to url for:
```
"https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2",
"[url=https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2]",
"C:\\Users\\user\\conda-bld\\linux-64\\foo-1.0-py27_0.tar.bz2",
"[url=C:\\Users\\user\\conda-bld\\linux-64\\foo-1.0-py27_0.tar.bz2]",
```
Ps. Also did some touchups where RustRover gave me a warning, spelling, grammer and code style. _boyscout_

fix: url parsing for namelessmatchspec and cleanup functions

---

crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_cache/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_digest/Cargo.toml
crates/rattler_index/Cargo.toml
crates/rattler_libsolv_c/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_macros/Cargo.toml
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/Cargo.toml
py-rattler/Cargo.lock

This PR marks the following crates as 1.0:
* `rattler_solve`
* `rattler_virtual_packages`
* `rattler_digest`
* `rattler_macros`
* `rattler_libsolv_c`
We mark them as 1.0 because their API has been stable enough for a long time and we also do not foresee any large refactors in the foreseeable future.

chore: mark some crates 1.0

---

crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_solve/src/libsolv_c/mod.rs
crates/rattler_solve/src/libsolv_c/output.rs
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_solve/tests/snapshots/backends__libsolv_c__virtual_package_constrains.snap
crates/rattler_solve/tests/snapshots/backends__resolvo__virtual_package_constrains.snap
test-data/channels/dummy/linux-64/repodata.json

If there was a package that had a constraint on a virtual package, e.g.:
```json
"constrains": ["__cuda >=12.1"],
```
and the virtual dependency was never explicitly required it was silently ignored. So even though your system would only support `cuda 11.8` the solver could select a version of a package that required a higher version. 
This PR solves this by adding explicit requirements on each specified virtual package. This behavior is also added for libsolv.

fix: constraints on virtual packages were ignored

---

crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/utils/url.rs

This should re-add the backslash to the channel.
This is to be forward compatible with the previous situation.

chore: add / for forward compatibility of the lockfile

---

crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/utils/path.rs
py-rattler/Cargo.lock

By adding the path parsing to the nameless matchspec I broke the parsing of `~= 1.2.3`. 
This PR changes a few things to better deal with that. 
- It now checks for `~/` to verify if it is a path
- We can now parse `~/channel_name::package` as the tilde is now actually parsed instead of seen as part of the string.
- Added a bunch more test cases to catch more issues in the future.

fix: parse `~=` as version not as path

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap

Fixes https://github.com/conda-incubator/rattler/issues/793
Continuation of https://github.com/conda-incubator/rattler/pull/792 that adds support for `1.2.3[channel=...]` and consolidates logic of parsing matchspec and namelessmatchspec some more.

feat: parse `channel` key and consolidate `NamelessMatchSpec`

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.toml
README.md
crates/file_url/CHANGELOG.md
crates/rattler/CHANGELOG.md
crates/rattler/src/lib.rs
crates/rattler_cache/CHANGELOG.md
crates/rattler_conda_types/CHANGELOG.md
crates/rattler_digest/CHANGELOG.md
crates/rattler_index/CHANGELOG.md
crates/rattler_libsolv_c/CHANGELOG.md
crates/rattler_lock/CHANGELOG.md
crates/rattler_lock/src/lib.rs
crates/rattler_macros/CHANGELOG.md
crates/rattler_networking/CHANGELOG.md
crates/rattler_package_streaming/CHANGELOG.md
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_repodata_gateway/CHANGELOG.md
crates/rattler_shell/CHANGELOG.md
crates/rattler_solve/CHANGELOG.md
crates/rattler_virtual_packages/CHANGELOG.md
py-rattler/docs/index.md
py-rattler/mkdocs.yml
py-rattler/pyproject.toml
py-rattler/rattler/package/about_json.py
test-data/dummy-about.json

Change all links from `conda-incubator` to `conda`

refactor: change links from conda-incubator to conda

---

py-rattler/docs/index.md

Fixing the example in the quickstart

docs(py-rattler): fix example path in mkdocs snippet

---

.github/workflows/docs.yaml
CHANGELOG.md
README.md
cliff.toml
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
py-rattler/pyproject.toml
py-rattler/rattler/package/about_json.py
test-data/dummy-about.json
test-data/environments/mamba_dev_extra.environment.yaml
test-data/test-server/README.md
test-data/test-server/repo/channeldata.json
test-data/test-server/repo/index.html
test-data/test-server/repo/recipes/test-package/meta.yaml
test-data/test-server/reposerver.py

We missed some more `conda-incubator` mentions, also move to much from `mamba-org`.

fix: move more links to the conda org from conda-incubator

---

crates/rattler_lock/src/utils/serde/pep440_map_or_vec.rs

This change is needed because of further changes in uv to pep440 markers. To make this compatible, we can luckily just do this change.

feat: default construct marker-tree

---

py-rattler/rattler/prefix/prefix_paths.py

Fixes #667. The `windows_python_entrypoint` attribute had an extra underscore on the python side which caused the error.
This attribute was misspelled. Sorry, had this diff ready a while ago and got sidetracked.

fix: windows python entrypoint script attribute in py-rattler

---

crates/rattler_lock/src/utils/serde/pep440_map_or_vec.rs
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_virtual_packages/src/cuda.rs
crates/rattler_virtual_packages/src/lib.rs

Hi, I know this is terrible, not elegant, etc, but I do think that having support for something in the spirit of CONDA_OVERRIDE_CUDA is necessary on academic HPC environments. Reasons include 
- only having internet access on the login node with no gpu
- launching jobs with submitit on login nodes with no gpu.
I'm not really used to writing rust, so would be greatful for some guidance.
Thanks

feat: Add support for `CONDA_OVERRIDE_CUDA`

---

crates/rattler-bin/src/commands/virtual_packages.rs
crates/rattler_virtual_packages/src/lib.rs
py-rattler/Cargo.lock
py-rattler/rattler/virtual_package/virtual_package.py
py-rattler/src/virtual_package.rs
py-rattler/tests/unit/test_override.py

In some places `None` would mean default for virtual package overrides. This PR streamlines the API so that `None` means no overrides.

refactor: make virtual package overrides none by default consistently

---

crates/rattler-bin/Cargo.toml
crates/rattler-bin/src/commands/create.rs
crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_virtual_packages/src/lib.rs

Fixes https://github.com/prefix-dev/pixi/issues/1922

fix: allow `gcs://` and `oci://` in gateway

---

crates/rattler_conda_types/src/environment_yaml.rs
crates/rattler_conda_types/src/lib.rs

With the addition of `EnvironmentYaml` to rattler, I'm taking another swing at adding exporting from Pixi (replacing https://github.com/prefix-dev/pixi/pull/1427 ), and using `EnvironmentYaml` to reuse code.
Currently the `MatchSpecOrSubSection` enum isn't published at the library level, so dependencies can't be added from `MatchSpecs` or Pip subsections. This publishes the enum so that it can be used for constructing `EnvironmentYaml`s from other representations.

fix: publish MatchSpecOrSubSection for env yaml

---

Cargo.toml
crates/rattler_solve/src/resolvo/mod.rs

Bumps [resolvo to `0.8.0`](https://github.com/mamba-org/resolvo/releases/tag/resolvo-v0.8.0) we especially want https://github.com/mamba-org/resolvo/pull/61 .

chore: bump resolvo 0.8.0

---

crates/rattler_conda_types/src/version_spec/mod.rs

It turns out that conda has a bug where MatchSpec parsing removes everything between round brackets. 
This is an issue with `rattler-build` since we want to produce packages that are compatible.
Our bracket printing algorithm was also not quite accurate because it was creating unnecessary brackets (AND should always have precedence over OR regardless of brackets or not).
This PR adds some tests and fixes this issue. 
However, it might invalidate existing lockfiles. I am not sure what to do about that. One could argue, that we should also have a MatchSpecWithSource type that retains the original string.

fix: improve when we print brackets

---

crates/rattler/src/install/transaction.rs

This adds the case that where the hash changed, which happened for my source build, that a re-install is triggered. I think this is the correct behavior, not sure if it will trigger *too* many re-installs but did not feel that would be the case.

fix: mark records as changed if hash Option value is different

---

py-rattler/tests/unit/test_matchspec.py

Tests for MatchSpec channel parsing as requested in https://github.com/conda/rattler/issues/869#issuecomment-2364170101.
Contrary to the observations in #869, both of these tests pass for me locally when running 
```console
$ cd py-rattler
$ pixi run --manifest-path pixi.toml -e test test
```
Which perhaps means the url parsing regressing is solved in the current `main`, but broken in the `0.6.3.` release?

test: add tests for py-rattler MatchSpec channel parsing

---

Cargo.toml
crates/rattler_solve/tests/snapshots/backends__resolvo__solve_with_error.snap
py-rattler/Cargo.lock
py-rattler/Cargo.toml

Bumps resolvo to `0.8.1` which includes some drastic performance improvements. 
This PR also bumps py-rattler to `0.7.1` so I can also make a release of the python bindings.

perf: update resolvo

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/link.rs
crates/rattler/src/install/snapshots/rattler__install__link__test__replace_long_prefix_in_text_file.snap
crates/rattler/src/install/snapshots/rattler__install__link__test__replace_python_shebang-2.snap
crates/rattler/src/install/snapshots/rattler__install__link__test__replace_python_shebang.snap
test-data/shebang_test.txt

This changes a little bit how we handle shebangs in text files.
When a shebang (after replacement) contains a `" "` space in the result we need to replace it with `/usr/bin/env ...` to make things work. This breaks execution in "non-activated" environments though. 
For Python scripts we can use another small trick: we can execute `/usr/bin/sh` and then run `exec "/path/to python with spaces/python" {args} ...` (which is also wrapped in a python comment). 
We are already doing this when we create Python entrypoints from scratch for noarch packages. I added this functionality here as well (duplicates code from `python.rs` though).

fix: fix-up shebangs with spaces

---

py-rattler/Cargo.lock
py-rattler/rattler/channel/channel.py
py-rattler/rattler/match_spec/match_spec.py
py-rattler/tests/unit/test_matchspec.py

This PR adds the tests described in #884.
It also provides a (reference) fix in `MatchSpec.channel`. I say "reference" because I imagine the maintainers may prefer to handle this in some other way (perhaps by pushing the url parsing I've done in Python here to the Rust layer?), in which case I will certainly have no objection to my "fix" being discarded. But I provide it nonetheless to indicate the general shape of a possible solution.
Thanks all! Happy to contribute to this further if I am able.

fix: return correct channel urls from `MatchSpec.channel.base_url`

---

crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/test_utils.rs

This fixes an issue where if you install `zlib=1.2` and then update to `zlib=1.3` all files were detected as "clobbered". 
This made changes really slow (e.g. when changing the version of Rust) because the un-clobbering is not really an optimized function and is expected to run only for a few files.

fix: self-clobber when updating/downgrading packages

---

crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs

JLAP previously had up to three copies of repodata simultaneously: the read bytes, the in-memory Serde representation, and the to-be-written bytes. Avoid having multiple copies of repodata in-memory simultaneously by streaming repodata reads and writes, which should bring us down to just one in-memory Serde copy.
_Does anybody have tips for recreating a more heavyweight JLAP patching scenario for the purpose of testing this patch's impact? For now, I am going on green test-cases and good vibes..._

refactor: stream JLAP repodata writes

---

crates/rattler_cache/src/package_cache/cache_key.rs
crates/rattler_cache/src/package_cache/cache_lock.rs
crates/rattler_cache/src/package_cache/mod.rs

This PR adds the ability in the cache to use the sha256 of a key as the cache lock file as well.
This is needed so that source build archives with the same paths but different contents are correctly replaced in the cache.

feat: use sha in cache lock file, needed for source builds.

---

crates/rattler/src/install/clobber_registry.rs

We are linking and unlinking files in parallel. We are ordering the operations per-package (meaning that for a given package, files are first unlinked, and then linked). However, if a file is installed by package A, and then "moves" to package B after an update the order of actions is not deterministic and can lead to crashes A.
It goes something like:
- package B tries to install new file
- package A removes file
- package B saw that file already exists, tries to remove file
- crash
https://github.com/prefix-dev/pixi/issues/1813
https://github.com/prefix-dev/pixi/issues/2287
With this PR we treat this kind of name-change as a "clobber". We install the new file to a `foo-clobber-by-B` location and rename it in the post-processing step. That should make things deterministic and every …

fix: removal / linking when package name changes

---

crates/rattler_index/src/lib.rs

This will fix issues in staged recipes where the `noarch` folder is created, but empty:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1057052&view=logs&jobId=dff6ff7b-316b-540a-5923-739df25f7012&j=dff6ff7b-316b-540a-5923-739df25f7012&t=2582809e-c3dc-5a5f-d883-fd3c8f9139aa

fix: always index noarch even if folder already exists

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__matchspec_to_string.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__tests__serialize_matchspec.snap

We were parsing brackets correctly, but we overrode it with `None`.
This fixes matchspecs like `foo * [build="*bla*"]`
For now this is no error when the build string is set twice (e.g. `foo * bar*[build="baz"]`). I am not sure if we _should_ treat that as an error (at least in strict mode?). Same goes for the version.
cc @jaimergp thanks for discovering this today!

fix: matchspec build / version from brackets and string serialization

---

.github/workflows/python-bindings.yml
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_solve/tests/backends.rs
py-rattler/rattler/exceptions.py
py-rattler/rattler/repo_data/package_record.py
py-rattler/src/error.rs
py-rattler/src/lib.rs
py-rattler/src/record.rs
test-data/channels/dummy/linux-64/repodata.json

feat: Add `PackageRecord::validate` function

---

Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_lock/src/snapshots/rattler_lock__test__v0__pypi-matplotlib-conda-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__path-based-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v4__pypi-matplotlib-lock.yml.snap
crates/rattler_lock/src/snapshots/rattler_lock__test__v5__flat-index-lock.yml.snap
py-rattler/Cargo.lock
py-rattler/Cargo.toml

feat: bump peps

---

crates/rattler_solve/src/resolvo/mod.rs

This fixes a hard crash in the solver when a locked package was used that did match the input spec but was otherwise completely unrelated from the candidates themselves.

fix: solver crash when using unrelated locked record

---

py-rattler/rattler/repo_data/gateway.py
py-rattler/src/repo_data/gateway.rs

Exposes the `names` functionality on repodata gateway to get all the package names of a channel/subdir.

fix: add repodata gateway names

---

crates/rattler_cache/src/lib.rs

This PR allows setting the cache directory using `RATTLER_CACHE_DIR` or `XDG_CACHE_HOME` and fallback to the current `dirs::cache_dir()` if needed.
I think it makes sense to have this logic into rattler directly but the use case was for rattler-build: https://github.com/prefix-dev/rattler-build/issues/1171

feat: set cache directory

---

crates/rattler_package_streaming/src/reqwest/tokio.rs

In https://github.com/conda/rattler/pull/837 locking logic was added to the download reporter to prevent multiple downloads.
This was clashing with the logic added in https://github.com/conda/rattler/pull/797 where, if we detect we're trying to download a zip that has data descriptors, we fallback to doing a full download and interrupt the streaming decompression download.
The issue comes from us not releasing the lock before attempting the second download, hitting this line https://github.com/conda/rattler/blob/8bb883536df52de46fd2c040228bb77d39c92607/crates/rattler_cache/src/package_cache/mod.rs#L439
As a fix, we report the previous download as completed before attempting the second one! Have verified in my custom setup that this works.

fix:  Release downloader lock before re-attempting fallback download 

---

py-rattler/Cargo.lock
py-rattler/rattler/package/paths_json.py
py-rattler/src/paths_json.rs

Adds lots of setters to the paths_json and related types.
Some of the `enum`'s could be exposed in a more Pythonic way but we can also do that later :)

feat: py-rattler - add more types to construct a paths.json type

---

crates/rattler_conda_types/src/channel/channel_url.rs
crates/rattler_conda_types/src/channel/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/utils/url_with_trailing_slash.rs

* `ChannelUrl` serializes without the trailing slash. Its information that is not needed and looks better without.
* `ChannelUrl::url` returns the `UrlWithTrailingSlash` type. This type is autoderefed into a `Url`.

feat: channel is serialized without trailing slash

---

crates/rattler/src/install/mod.rs
crates/rattler/src/install/unlink.rs

Attempt to move files to .trash folder if they are in use, this should solve #578. The issue is that on Windows we cannot delete files that are in use. When using a global package cache and hardlinking files into environments this means that if a given DLL or exe is in use in any environment with the same package the deletion files. But we can rename the hardlink. Conda and mamba have similar fallback behaviour.
The solution in this PR is slightly different than the ones used in conda and mamba as far as I am aware. This PR:
* Creates a folder in `.trash` in the root of the environment rather than having a file like mamba_trash.txt to keep track of all the files which could not be deleted. Then a separate empty_trash procedure should simply attempt to delete all files in the .trash folder …

feat: Move files to .trash folder if they are in use

---

py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/pixi.lock
py-rattler/pixi.toml
py-rattler/rattler/lock/lock_file.py
py-rattler/rattler/networking/__init__.py
py-rattler/rattler/networking/client.py
py-rattler/rattler/networking/middleware.py
py-rattler/src/lib.rs
py-rattler/src/networking/client.rs
py-rattler/src/networking/middleware.rs
py-rattler/tests/unit/test_package_streaming.py

This PR adds the ability to use the GCS middleware from python, it uses the underlying gcs middlware type from rattler directly.
This feature also adds the gcs feature as a default to the networking crate in py-rattler.
A simple instantiation test has been written. Any other test that could be added?
I've also added a `repl` task to start an ipython session which you can use to mess around with the API

feat: add gcs middleware

---

py-rattler/Cargo.toml

We noticed that the `py-rattler` PyPI release ignores custom certificates bundles.
We added the `reqwest/rustls-tls-native-roots` library to the `rustls-tls` feature in accordance with [how Pixi does it](https://github.com/prefix-dev/pixi/blob/1650d6a9ae4478ac7c312923579ecdba7de1824a/Cargo.toml#L168).
We tested this locally and it seems to resolve our issue.

fix: Add reqwest/rustls-tls-native-roots to rustls-tls feature in py-rattler

---

Cargo.toml
py-rattler/Cargo.lock
py-rattler/Cargo.toml

Upgrade reqwest middleware and retry crates. This upgrade is needed so that we can start using these versions in pixi, in conjuction with the uv crates.

feat: upgrade reqwest middleware and retry

---

crates/rattler_repodata_gateway/src/gateway/query.rs

Dont fetch repodata if there are no specs or no platforms/channels in the first place.

fix: short circuit on no-op

---

crates/rattler/src/install/mod.rs
crates/rattler/src/install/unlink.rs
crates/rattler_cache/Cargo.toml
crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_package_streaming/src/tokio/fs.rs
crates/rattler_package_streaming/tests/extract.rs
crates/rattler_repodata_gateway/src/fetch/jlap/mod.rs
crates/rattler_repodata_gateway/src/fetch/mod.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/index.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/mod.rs
crates/rattler_repodata_gateway/src/utils/mod.rs

This should improve error messages for file operations driven by tokio

feat: use `fs-err` also for tokio

---

.github/workflows/rust-compile.yml
crates/rattler_networking/src/gcs_middleware.rs

Unfortunately a bug slipped in where we were sending `Bearer Bearer <token>` (ie. one Bearer too much). 
This fixes it and adds a test. I also added credential for a test account in the `GOOGLE_CLOUD_TEST_KEY_JSON` secret. This can access a bucket in the prefix-dev GCS (`conda-channel-test/test-channel`).
To use GCS channels, you need to first login using the `gcloud` CLI tool. For automatic discovery, rattler expects the `~/.config/gcloud/application_default_credentials.json` file to be available (or the `GOOGLE_APPLICATION_CREDENTIALS` env var to contain the JSON contents). 
To login, you can use `gcloud auth application-default login` which will automatically create the JSON file in the right place.
```
gcloud iam service-accounts create gh-action-test-bucket-reader \
--display-name …
```

fix: GCS channels and add test

---

.github/workflows/release-python.yml
py-rattler/pyproject.toml

~~attempting to fix aarch64 windows build for py-rattler~~
I could not get CI to succeed for `aarch64-windows-msvc-pc`. The biggest problem seems to be that `ring` is a non-optional dependency of `jsonwebtoken` which is a non-optional dependency of `google-cloud-auth`.
At this point I just gave up. We'll revisit this later.

chore: remove aarch64-windows-msvc-pc wheel

---

py-rattler/rattler/repo_data/gateway.py
py-rattler/src/repo_data/gateway.rs

I am using a private conda channel and I am able to `rattler.install`, but not `rattler.solve`!  This change allows authenticating the solver as well. Fixes #973 
I can't think of a reasonable way to unit test this, but I did test it via `pixi run repl`.

feat: allow using an authenticated `Client` in `Gateway`

---

crates/rattler_conda_types/src/platform.rs

We already have this for `Platform`. I need it in `rattler-build` to make sure we can set everything to `false` instead of undefined, and then throw errors when encountering actually undefined values.

feat: add `EnumIter` to `Arch`

---

crates/rattler_cache/src/package_cache/mod.rs

This PR fixes an issue where the package cache would be repopulated even though this was not required. This was because the individual cache entries shared the same lock file. For example these packages would all use the same lock file name (`cffi-1.17.lock`):
```
cffi-1.17.0-py38h4cb3324_0
cffi-1.17.1-py311he736701_0
cffi-1.17.1-py312h4389bb4_0
cffi-1.17.1-py313ha7868ed_0
```
This PR fixes this by correctly computing the lock file name for each entry (e.g. `cffi-1.17.1-py313ha7868ed_0.lock`).

fix: package cache lock file_name was incorrect

---

Cargo.toml
crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/link_script.rs
crates/rattler_cache/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_conda_types/benches/prefix_record_from_path.rs
crates/rattler_conda_types/src/environment_yaml.rs
crates/rattler_conda_types/src/explicit_environment_spec.rs
crates/rattler_conda_types/src/lib.rs
crates/rattler_conda_types/src/prefix_record.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_libsolv_c/Cargo.toml
crates/rattler_solve/src/libsolv_c/wrapper/repo.rs
crates/tools/src/libsolv_bindings.rs

I have tried out rayon to parallelize the loading of `PrefixRecord` files. The results look pretty good:
```
load_serially           time:   [10.369 ms 10.403 ms 10.440 ms]
load_as_prefix_record   time:   [697.90 ns 699.63 ns 701.53 ns]
load_as_package_record  time:   [698.94 ns 700.45 ns 702.11 ns]
```
Unfortunately loading the subset (`PackageRecord`) doesn't seem to be a big improvement.

feat: speed up `PrefixRecord` loading

---

crates/rattler_conda_types/src/package/mod.rs

I saw a lot of file system activity on macOS related to reading package cache files. 
The way we were reading them was not optimal. `std::fs::read_to_string` does a better job: it looks at the file, checks the size, and uses the size as a hint to first allocate the string and then allocate the buffer for the reading. So I hope this will improve this a bit.

perf: read json to memory before parsing

---

py-rattler/src/networking/mod.rs
py-rattler/tests/unit/test_fetch_repo_data.py

When using the py-rattler library, the `fetch_repo_data` method incorrectly sets the `subdir` on `SparseRepoData` instances so if a channel is missing `subdir` on `PackageRecords`, it tries to append the bad subdir value to the url which can cause a panic.
This can be seen with this example
```
import asyncio
from pathlib import Path
from rattler import fetch_repo_data, solve_with_sparse_repodata
from rattler.channel import Channel, ChannelConfig, ChannelPriority
from rattler.platform import Platform
from rattler.match_spec import MatchSpec
from rattler.virtual_package import VirtualPackage
async def main():
channel_config = ChannelConfig("https://repo.anaconda.com/pkgs/")
channels = [Channel("free", channel_configuration=channel_config)]
sparse = await fetch_repo_data(
channels=channels, …
```

fix: Create SparseRepoData with correct subdir in py_fetch_repo_data

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__tests__serialize_matchspec.snap
crates/rattler_conda_types/src/version_spec/constraint.rs
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs
crates/rattler_conda_types/src/version_spec/snapshots/rattler_conda_types__version_spec__parse__test__exact_strict.snap
crates/rattler_repodata_gateway/src/gateway/mod.rs
py-rattler/Cargo.lock
py-rattler/tests/unit/test_gateway.py
py-rattler/tests/unit/test_solver.py

This PR makes parsing even stricter. With these changes, `foo 1.2.3` throws an error and suggests either `==1.2.3`, or `1.2.3.*`.
Note: there seems to be a bug (not sure if new?) when parsing `1!1.2.3.*` - it says "ExpectedEof".

feat: make strict parsing even stricter

---

Cargo.toml
crates/file_url/Cargo.toml
crates/rattler/src/install/mod.rs
crates/rattler_cache/Cargo.toml
crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_libsolv_c/Cargo.toml
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_solve/tests/snapshots/backends__resolvo__solve_with_error.snap

Updated most dependencies. Only `generic-array` continues to be held back so that serialization is easy with sha2 crates (that use an older version of generic-array).

chore: update dependencies

---

crates/rattler_sandbox/src/sandbox/mod.rs

Looks like this was forgotten which makes network always disabled.

feat: wire up network config for sandbox

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs

Fixes #1004 
Fixes parsing of `numpy>=2.*.*` in lenient mode. Note that this makes no sense and it is just interpreted as `>=2`.

fix: parsing of >=2.*.*

---

crates/rattler/src/install/mod.rs
crates/rattler_conda_types/src/build_spec/mod.rs
crates/rattler_conda_types/src/match_spec/matcher.rs
crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__tests__serialize_json_matchspec.snap
crates/rattler_conda_types/src/version_spec/mod.rs

Implements `Deserialize` for some types that basically convert to a string.
We used to do this a lot:
```rust
/// The version spec of the package (e.g. `1.2.3`, `>=1.2.3`, `1.2.*`)
#[serde_as(as = "Option<DisplayFromStr>")]
pub version: Option<VersionSpec>,
/// The build string of the package (e.g. `py37_0`, `py37h6de7cb9_0`, `py*`)
#[serde_as(as = "Option<DisplayFromStr>")]
pub build: Option<StringMatcher>,
``` 
With this change that is no longer needed.

feat: add deserialize from string for types

---

crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_package_streaming/src/reqwest/tokio.rs
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/fetch/mod.rs
crates/rattler_repodata_gateway/src/gateway/remote_subdir.rs

This PR adds retry behavior to failed `repodata.json.*` downloading if an io error is encountered. 
I tried adding a test for this but I failed to create a situation where during streaming the server exits.

fix: retry failed repodata streaming on io error

---

crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_nameless_from_string_Strict.snap
crates/rattler_conda_types/src/version_spec/mod.rs
crates/rattler_conda_types/src/version_spec/parse.rs
crates/rattler_conda_types/src/version_spec/snapshots/rattler_conda_types__version_spec__parse__test__exact_strict.snap

This exposes the `ParseConstraintError` type and removes some nesting of error text because it didnt make it much clearer. I need this so that I can provide a migration path in pixi.

feat: expose ParseConstraintError

---

crates/rattler_conda_types/src/match_spec/mod.rs
crates/rattler_lock/src/lib.rs
crates/rattler_virtual_packages/src/lib.rs
test-data/conda-lock/v6/numpy-as-pypi-lock.yml
test-data/conda-lock/v6/python-from-conda-only-lock.yml

I'm working on improving `pixi`'s implementation of the virtual package requirements.
I was reading the virtual packages from the `depends` field of the package record, which could be parsed as `MatchSpecs`. So I implemented this. But to avoid the huge overhead of parsing **all** dependencies, I later reverted to doing the `starts_with("__")` check again in pixi on the strings. I kept this feature in `rattler_conda_types::MatchSpec` however, as it seems like a useful function.
This PR also allows you to compare `MatchSpecs` with `GenericVirtualPackage`s, which I use to validate the system virtual packages with the `MatchSpecs` of a virtual dependency.
I've also added some small convenience functions to make building the logic on the lockfile a little easier.

feat: Match GenericVirtualPackage with MatchSpec

---

crates/rattler_conda_types/src/platform.rs
crates/rattler_virtual_packages/src/lib.rs

This PR adds PPC32 BE support to rattler. It goes hand-in-hand with the micromamba PR: https://github.com/mamba-org/mamba/pull/3707
Both rattler and rattler-build are verified to build and run on the Nintendo Wii U using the latest rust build (1.84.0).
Just a note: PPC32 BE builds should still run on ppc64 and ppc64le (in big endian mode), but I do not have any ppc64 devices to test with.

feat: Add linux-ppc (PPC32 BE) build support to rattler

---

Cargo.toml
crates/rattler_virtual_packages/Cargo.toml
crates/rattler_virtual_packages/src/lib.rs
crates/rattler_virtual_packages/src/linux.rs
crates/rattler_virtual_packages/src/win.rs

This PR aligns our virtual package implementation with the upcoming [virtual package cep](https://github.com/conda/ceps/pull/103). I think most of the changes proposed in the CEP make a lot of sense so I feel we can already merge this PR before the CEP is accepted. 
In particular, I made the following changes:
* `__win` now also reports the version of Windows.
* `__win` can be overridden with `CONDA_OVERRIDE_WIN`
* `__linux` can be overridden with `CONDA_OVERRIDE_LINUX`
* `__archspec` can be overriden with `CONDA_OVERRIDE_ARCHSPEC`
* `__archspec` falls back to deriving the archspec from the platform if it could not be determined.
* `__archspec` is added as `__archspec=1=0` if the no archspec could be determined for the current platform.
Changes I explicitly did not make (also left a …

feat: align with upcoming virtual package cep

---

py-rattler/rattler/networking/__init__.py
py-rattler/rattler/networking/fetch_repo_data.py
py-rattler/rattler/repo_data/gateway.py
py-rattler/src/lib.rs
py-rattler/src/networking/mod.rs
py-rattler/src/repo_data/gateway.rs
py-rattler/tests/unit/test_fetch_repo_data.py

I sometimes run into zstd decoding errors when trying to fetch repodata and was wanting to be able to disable zstd from py-rattler.  This PR exposes the FetchRepoDataOptions struct in rust to python.
I originally had the python class in `gateway.py` but that was causing a circular import when trying to import it in `fetch_repo_data.py` so I moved it.

feat: Expose FetchRepoDataOptions to py-rattler

---

README.md

That link works for both GitHub and mkdocs

docs: fix anchor link

---

py-rattler/mkdocs.yml
py-rattler/pixi.lock
py-rattler/pixi.toml

This improves the rendering of the function signatures. This needed:
- upgrade of `mkdocstrings`
- `ruff` for formatting
- option `separate_signature: true`
Before:
Now:

docs: improve py-rattler docs

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/installer/indicatif.rs
crates/rattler/src/install/transaction.rs

Hey there, I'm back with another super edge case!
While using rattler I started seeing that installing new packages on top of my existing environment was leading me to get invalid authentication errors when downloading packages, which lead me to find the edge case that follows.
- Let's say a user uses basic authentication to authenticate requests for packages to their onw private conda repository. Which means the channel URL will look like `https://user:password@[their own repo url]` 
- Let's say that these tokens are invalidates and rolled in a short time range -> in this case tokens are rolled every 1 hour 
- Let's say at 1PM I create an env containing `packageA-1.1.1` and `python-3.11.8`. -> **succeeds**
- Let's say at 2:30PM I want to install a packageB on top of this environment. -> …

fix: Use new PackageRecord when issuing reinstallation in Transaction::from_current_and_desired

---

crates/rattler_cache/src/consts.rs

everywhere we use dash for folder names instead of underscore.
I think it would be good to use the same approach for run-exports cache

fix: use run-exports

---

js-rattler/crate/version.rs
js-rattler/package-lock.json
js-rattler/src/Version.test.ts
js-rattler/src/Version.ts

feat: add Version.compare to wasm Version

---

pixi.toml
scripts/activate_linux.sh

I mostly had to switch from native-tls to rust-tls.
Annoyingly, I didn't manage to convince the build-process to find libclang needed to compile libsolv so I skip that test for now
Tagging @pavelzw since you also hit this problem recently IIRC

fix: compiling with pixi on linux

---

Cargo.lock
crates/rattler_index/Cargo.toml
crates/rattler_index/src/lib.rs

xref https://github.com/conda/rattler/pull/1076#discussion_r1974614762
this doesn't get rid of the other bytes cloning in `package_record_from_conda_reader` and `package_record_from_tar_bz2_reader`, this needs to be fixed in another PR.

refactor: Create reader from opendal buffer

---

crates/rattler_menuinst/src/windows.rs

Needed for testing in `pixi` blocking: https://github.com/prefix-dev/pixi/pull/3226
Tested by using this version of rattler locally in the pixi dependencies

fix: create test directories

---

Cargo.lock
js-rattler/Cargo.lock
js-rattler/Cargo.toml
js-rattler/crate/error.rs
js-rattler/crate/gateway.rs
js-rattler/crate/lib.rs
js-rattler/src/Gateway.test.ts
js-rattler/src/Gateway.ts
js-rattler/src/PackageName.test.ts
js-rattler/src/PackageName.ts
js-rattler/src/Platform.ts
js-rattler/src/index.ts
js-rattler/src/solve.test.ts
js-rattler/src/solve.ts
js-rattler/src/typeUtils.ts

Adds the `Gateway` object to the javascript bindings. I did not yet expose the most important method `query` in this PR yet, Ill do that in a followup PR. I left this out because it also requires exposing `RepoDataRecord` and there are still a lot of types missing to properly do that.
I also added types for `Platform` and `PackageName`. Both are completely defined in typescript instead of using bindings because I think that provides the best ergonomics. One cool feature that I also implemented is that we can check at compile time that a string literal is actually a valid package name!

feat(js): add Gateway object

---

crates/rattler_menuinst/src/windows.rs

Otherwise, Windows will not know what to do with it

fix: shortcut filename

---

Cargo.lock
Cargo.toml

The release PR failed after updating the lockfile. Because of an update of the aws-config crate. This pr locks that and updates the rest of the lock file accordingly

fix: lock aws-config to older version

---

.github/workflows/docs.yaml
.github/workflows/enforce-sha.yml
.github/workflows/js-bindings.yml
.github/workflows/lint-pr.yml
.github/workflows/pre-commit.yaml
.github/workflows/python-bindings.yml
.github/workflows/release-python.yml
.github/workflows/release-rust.yaml
.github/workflows/rust-compile.yml

- Pin Github actions to SHA (they can still be updated by dependabot)
- Enforce that SHA is used for github actions
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/

ci: pin github actions

---

crates/rattler_menuinst/src/windows.rs
crates/rattler_repodata_gateway/src/gateway/builder.rs
crates/rattler_repodata_gateway/src/gateway/mod.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/tokio/index.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/tokio/mod.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/wasm/index.rs
crates/rattler_repodata_gateway/src/gateway/sharded_subdir/wasm/mod.rs
crates/rattler_repodata_gateway/src/lib.rs

To control the maximum number of concurrent requests you can pass a number to `with_max_concurrent_requests`. This will limit the maximum number of requests that are executed concurrently. 
However, sometimes another part of the application might also be performing requests which could cause more requests to be made. This PR modifies the code to allow passing in a semaphore to control the concurrency which can be shared with other parts of the code.

feat: allow to pass a semaphore for concurrency control

---

Cargo.lock
crates/rattler/src/install/unlink.rs

This might fix issues in the `pixi` CI.

fix: use `create_dir_all` for `.trash` directory on Windows

---

crates/rattler_index/src/lib.rs

cloning package bytes could get out of hand quickly if you have large packages

fix: Don't clone package bytes in rattler-index

---

js-rattler/src/esm.ts

Rattler was using a top-level await (actually not even needed as it was awaiting a synchronous function), which is not allowed in some contexts like service workers.

fix(JS): Remove non-needed top-level awaits

---

crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_index/src/lib.rs

A follow-up of this issue https://github.com/conda/rattler/issues/1179 to unblock myself from using `pixi` at work. I'm not really a Rust developer but it looks like this change is easy enough for me to handle, feedback is welcome.
Did some preliminary tests integrating with `pixi` seems to suggest this fixes my issue, no test was added because this is a data model change, and should be protected by any existing ones.

fix: allow empty info key in repodata.json (#1179)

---

crates/rattler_menuinst/src/schema.rs
crates/rattler_menuinst/src/windows.rs

Update the default value of `quicklaunch` to match menuinst schema.
- https://conda.github.io/menuinst/reference/#menuinst._schema.Windows.quicklaunch
- https://github.com/conda/menuinst/issues/244
- https://github.com/conda/menuinst/pull/272

refactor: change default value of  menuinst windows `quicklaunch` to `false`

---

Cargo.lock
Cargo.toml
crates/rattler_networking/Cargo.toml
js-rattler/Cargo.lock

I think they broke because of updating `getrandom`. Let's see. cc @prsabahrami

chore: fix js bindings

---

Cargo.lock
crates/rattler_menuinst/src/windows.rs

Add missing windows start menu shortcut installation.
In menuinst, the windows start menu shortcut is installed implicitly. This pr will match the windows installation behaveor to menuinst.
This could fix https://github.com/prefix-dev/pixi/issues/3400

fix: install windows start menu shortcut

---

crates/rattler_repodata_gateway/src/fetch/mod.rs
crates/rattler_repodata_gateway/src/fetch/with_cache.rs

Does printing the PathBuf with `{1:?}` work?

feat: more helpful error when failing to persist repodata

---

Cargo.toml

This downgrades `async-compression` since we otherwise encounter a dependency conflict on the pixi side:
```
error: failed to select a version for `async-compression`.
... required by package `uv-extract v0.0.1 (https://github.com/astral-sh/uv?tag=0.6.9#3d946027)`
... which satisfies git dependency `uv-extract` of package `uv-distribution v0.0.1 (https://github.com/astral-sh/uv?tag=0.6.9#3d946027)`
... which satisfies git dependency `uv-distribution` of package `pixi v0.44.0 (/var/home/julian/Projekte/github.com/prefix-dev/pixi-1)`
versions that meet the requirements `^0.4.12` are: 0.4.22, 0.4.21, 0.4.20, 0.4.19, 0.4.18, 0.4.17, 0.4.16, 0.4.15, 0.4.14, 0.4.13, 0.4.12
the package `async-compression` links to the native library `lzma`, but it conflicts with a previous package which links to …
```

fix: downgrade `async-compression`

---

crates/rattler_digest/src/serde.rs

This allows us to derive `Clone` for more types on the pixi side

feat: derive `Debug` and `Clone` for `SerializableHash`

---

Cargo.lock
Cargo.toml
crates/rattler_package_streaming/src/read.rs

With newer simd-json, you also need a newer version of a transient dependency which needs edition2024, which requires a Rust 1.85, which in turn fails to compile with uv on the pixi side
zip 2.6.0 introduced a breaking change without bumping the version number accordingly. This makes it very easy to get to a situation where rattler refuses to compile

fix: upgrade simd-json and downgrade zip

---

Cargo.lock
crates/rattler_cache/src/package_cache/cache_key.rs
crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_digest/Cargo.toml
crates/rattler_digest/src/lib.rs

This PR is trying to solve an issue that was kind of already mentioned in this comment (cc @baszalmstra):
https://github.com/conda/rattler/blob/c7e2197d0bf8cd50a629e352e644ced7c752d9e7/crates/rattler_cache/src/package_cache/cache_key.rs#L7
Over at Palantir, users have the ability to generate custom conda packages and publish them to a private conda channel. The cache key currently consists of a `name`, `version`, and a `build_string` (and an optional `sha256` that we do not use in our custom conda packages).
Unfortunately, we set the `build_string` to a hardcoded value of `py_0`, so realistically the cache key only consists of the `name` and the `version` for those packages.
One of our forward deployed engineers ran into an issue where they tried to install a conda package with the same …

fix: Add location to the cache key

---

crates/rattler/src/install/installer/mod.rs
crates/rattler/src/install/mod.rs

Closes #1238 
This PR changes the `InstallOptions::target_prefix` to `Option<PathBuf>`.

refactor: change `InstallOptions::target_prefix` to `Option<PathBuf>`

---

crates/rattler_lock/src/conda.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/parse/models/v6/conda_package_data.rs
crates/rattler_lock/src/parse/models/v6/mod.rs
crates/rattler_lock/src/parse/models/v6/source_data.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v6__sources-lock.yml.snap
crates/rattler_lock/src/source.rs
test-data/conda-lock/v6/sources-lock.yml

This PR adds the `sources` field to source dependencies to allow specifying that a given dependency should come from a specific source location. This will enable us to lock where dependencies should come from.
This is WIP for now because I need to add way more tests.

feat: add source location

---

Cargo.lock
crates/rattler_lock/Cargo.toml
crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/options.rs
crates/rattler_lock/src/parse/deserialize.rs
crates/rattler_lock/src/parse/serialize.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_lock/src/snapshots/rattler_lock__test__v6__options-lock.yml.snap
crates/rattler_lock/src/utils/serde/mod.rs
test-data/conda-lock/v6/options-lock.yml

Adds resolver options to the lock file. These options strongly modify the outcome of the solver. They are stored along the locked package so programs can choose to invalidate the content if these options changed.
The options stored are:
* channel-priority: disabled or strict.
* solve strategy: whether the solver selected the highest versions or the lowest.
* exclude-newer: whether packages after a certain date were excluded.
These correspond to options used by `rattler_solve`.
These changes should both be backward- and forward-compatible. E.g. older clients will ignore the new fields, newer clients with older lock-files will use sane defaults.

feat: add resolver options to lock-file

---

Cargo.lock
Cargo.toml
crates/rattler_solve/Cargo.toml
crates/rattler_solve/src/resolvo/mod.rs

This bumps `resolvo` to `0.9.0`. This should not change much but slightly reduce memory usage. I also removed a few unused dependencies.

chore: bump resolvo 0.9.0

---

crates/rattler_lock/src/builder.rs
crates/rattler_lock/src/lib.rs
crates/rattler_lock/src/options.rs
crates/rattler_lock/src/parse/deserialize.rs
crates/rattler_lock/src/parse/serialize.rs
crates/rattler_lock/src/parse/v3.rs

Renames the `options` struct to be more in line with our other crates and reexports some fields so that an import of `rattler_solve` is not perse needed in downstream crates.

fix: rename struct and reexport

---

Cargo.toml
crates/rattler-bin/Cargo.toml
crates/rattler/Cargo.toml
crates/rattler_cache/Cargo.toml
crates/rattler_conda_types/Cargo.toml
crates/rattler_index/Cargo.toml
crates/rattler_lock/Cargo.toml
crates/rattler_menuinst/Cargo.toml
crates/rattler_package_streaming/Cargo.toml
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_shell/Cargo.toml
crates/rattler_solve/Cargo.toml
crates/rattler_virtual_packages/Cargo.toml
js-rattler/Cargo.lock

Pin all the workspace dependencies. 
release-plz automatically bumps any workspace member whose dependencies have changed. This means that crates are always bumped in tandem. This is useful because it means we also always test the crates together that will be used together.
So given that crates are always updated in tandem we choose to pin the member crates together as well.

refactor: lock workspace member dependencies

---

crates/rattler_conda_types/src/menuinst/mod.rs
crates/rattler_menuinst/src/lib.rs
crates/rattler_menuinst/src/windows.rs

In recent pixi 0.46.0, windows desktop, start menu, quick launch shortcut are all installed successfully. But start menu and quick launch shortcut ink file do not point to the right command, while desktop shortcut do the right thing.
tasks:

fix: menuinst windows shorcut path

---

py-rattler/rattler/repo_data/gateway.py

if we use `List[T | K]` as argument type then it doesn't accept `list[T]` or `list[K]`, which is actually allowed.

refactor(py): improve `Gateway` typing

---

crates/rattler_conda_types/src/package/index.rs

https://github.com/conda/rattler/pull/1303#discussion_r2091102800

fix: Skip serializing if purls are None

---

py-rattler/rattler/prefix/prefix_paths.py
py-rattler/src/prefix_paths.rs

Fixes #1340 
Renames `entrypoint` to `entry_point` (just as we have in Rust).

fix!: rename entrypoint to entry_point

---

crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_repodata_gateway/src/sparse/mod.rs
test-data/channels/dummy/linux-64/repodata.json

Fixes #1330 
Packages names werent properly deduplicated in the sparse repodata when both .conda and .tar.bz2 packages were present. This PR fixes that. Also added a test to verify this behavior.

fix: properly dedup package names

---

crates/rattler_conda_types/src/repo_data/sharded.rs

Fixes #1326 
Adds the `created_at` field to the sharded subdir info. The field can be optional.

fix: add missing `created_at` in shards

---

py-rattler/Cargo.lock
py-rattler/Cargo.toml
py-rattler/rattler/repo_data/sparse.py
py-rattler/src/repo_data/sparse.rs
py-rattler/src/solver.rs

This PR adds `SparseRepoData.close()` which will forcefully close any resource related to the instance. This is useful because otherwise one has to depend on the Python garbage collector.
Hopefully this helps with https://github.com/conda-incubator/conda-rattler-solver/issues/7

feat(py): allow forcefully closing SparseRepoData

---

Cargo.lock
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__base_url_packages.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages-2.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__test__serialize_packages.snap
crates/rattler_repodata_gateway/Cargo.toml
crates/rattler_repodata_gateway/src/gateway/local_subdir.rs
crates/rattler_repodata_gateway/src/sparse/mod.rs
crates/rattler_repodata_gateway/src/sparse/snapshots/rattler_repodata_gateway__sparse__test__only_conda@both.snap
crates/rattler_repodata_gateway/src/sparse/snapshots/rattler_repodata_gateway__sparse__test__only_conda@only-conda.snap
crates/rattler_repodata_gateway/src/sparse/snapshots/rattler_repodata_gateway__sparse__test__only_conda@only-tar-bz2.snap
crates/rattler_repodata_gateway/src/sparse/snapshots/rattler_repodata_gateway__sparse__test__only_conda@prefer-conda.snap
crates/rattler_solve/benches/bench.rs
crates/rattler_solve/benches/sorting_bench.rs
crates/rattler_solve/tests/backends.rs
crates/rattler_solve/tests/sorting.rs
py-rattler/Cargo.lock
py-rattler/rattler/__init__.py
py-rattler/rattler/repo_data/__init__.py
py-rattler/rattler/repo_data/sparse.py
py-rattler/rattler/solver/solver.py
py-rattler/src/lib.rs
py-rattler/src/repo_data/sparse.rs
py-rattler/src/solver.rs
test-data/channels/dummy/linux-64/repodata.json

Fixes #1328
Fixes #1329 
This PR adds the ability to tell SparseRepoData to only parse `.conda` or `.tar.bz2` packages. 
Also adds the `use_only_tar_bz2` to `solve_with_sparse_repodata` to only read `.tar.bz2`. Otherwise, prefers `.conda` packages.

feat: control over selection of .conda and .tar.bz2

---

crates/rattler_repodata_gateway/src/gateway/local_subdir.rs
crates/rattler_repodata_gateway/src/sparse/mod.rs
py-rattler/rattler/repo_data/sparse.py
py-rattler/src/match_spec.rs
py-rattler/src/repo_data/sparse.rs

Adds the ability to load all repodata records from a SparseRepoData, query packages based on matchspec, and return the total number of packages.

feat(py): query based on matchspec and package count

---

js-rattler/crate/solve.rs
js-rattler/src/solve.test.ts

Now, the js-rattler solver does not accept previously installed packages but it should take care about it. 
This PR has next changes:
- adding locked_packages to the solver
- if a locked package does not have depends then this data will be taken from repodata
For example, using this code
```
const test = await simpleSolve(
["xeus-python ", "numpy"],
["https://repo.prefix.dev/emscripten-forge-dev","conda-forge"
],
["emscripten-wasm32", "noarch"],
[{
build: "py313h027658c_2",
buildNumber,
filename: "xeus-python-0.17.4-py313h027658c_2.tar.bz2",
packageName: "xeus-python",
repoName: "https://repo.prefix.dev/emscripten-forge-dev/",
url: "https://repo.prefix.dev/emscripten-forge-dev/emscripten-wasm32/xeus-python-0.17.4-py313h027658c_2.tar.bz2",
version: "0.17.4",
}]
);
console.log('test',test); …
```

feat: Adding locked packages to the js-rattler solver

---

crates/rattler_repodata_gateway/src/gateway/sharded_subdir/tokio/index.rs

The progress reporter was not finished when the request was determined unmodified.

fix: end progress sharded repodata

---

py-rattler/pixi.lock
py-rattler/pixi.toml

Trying to use rust-analyzer with py-rattler and ran into the error 
> can't load standard library, try installing `rust-src` sysroot_path=/Volumes/workspace/rattler/py-rattler/.pixi/envs/test
I found [this thread](https://discord.com/channels/1082332781146800168/1331668634707431506/1331668875820929124) from @lucascolley where just adding rust-src to the environment was proposed, so here I'm actually gonna do it 😄

fix: add rust-src to py-rattler

---

crates/rattler_conda_types/src/match_spec/parse.rs
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Lenient.snap
crates/rattler_conda_types/src/match_spec/snapshots/rattler_conda_types__match_spec__parse__tests__test_from_string_Strict.snap

Fixes an issue where `=0.*,>=0.4.1` was parsed as `.. =0.*[build=",>=0.4.1"]`.

fix: parsing of `=0.*,>=0.4.1`

---

py-rattler/rattler/match_spec/nameless_match_spec.py
py-rattler/tests/unit/test_matchspec.py

closes #1390
As noted there, this is the identical fix as @baszalmstra applied to `MatchSpec.channel` in #885, except for `NamelessMatchSpec.channel`. I have mirrored all the `MatchSpec` unit tests for `NamelessMatchSpec`. Without this fix, there are two test failures in the added tests (which accurately represent the bug described in #1390):
```
=============================================================================================================================== FAILURES ===============================================================================================================================
___________________________________________________________________________________________________________ test_parse_channel_from_url_filesystem_nameless …
```

fix: return correct channel urls from `NamelessMatchSpec.channel.base_url`

---

crates/rattler_shell/src/shell/mod.rs
crates/rattler_shell/src/shell/snapshots/rattler_shell__shell__tests__bash.snap
crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__activation_script_bash.snap
crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__test_activation_script_bash_append.snap
crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__test_activation_script_bash_prepend.snap
crates/rattler_shell/src/snapshots/rattler_shell__activation__tests__test_activation_script_bash_replace.snap

On Windows, activating an environment with Git Bash fails. I experienced this issue trying to use the `pixi shell-hook` command that produces output like:
```
$ pixi shell-hook
export Path="/c/Dev/rattler/.pixi/envs/default;/c/Dev/..."
export CONDA_PREFIX="C:\Dev\rattler\.pixi\envs\default"
export PIXI_PROJECT_ROOT="C:\Dev\rattler"
export PIXI_PROJECT_NAME="rattler"
```
This is incorrect, because of using the ";" instead of ":" separator in the PATH and not escaping the "\\" characters in the other paths that appear.
By using shlex::try_quote, these variables can be set correctly. Because setting the PATH used the primitive for setting an environment variable, that had to change to explicitly use double-quotes, so that the included ${PATH} is evaluated instead of handled literally. …

fix: Quote values in bash activation with shlex

---

crates/rattler-bin/Cargo.toml
crates/rattler_index/Cargo.toml
crates/rattler_networking/Cargo.toml
crates/rattler_networking/src/authentication_middleware.rs
crates/rattler_networking/src/authentication_storage/backends/file.rs
crates/rattler_networking/src/authentication_storage/backends/memory.rs
crates/rattler_networking/src/authentication_storage/backends/mod.rs
crates/rattler_networking/src/authentication_storage/mod.rs
crates/rattler_networking/src/authentication_storage/storage.rs
js-rattler/Cargo.lock
py-rattler/Cargo.toml

I was looking into the failing build in #1378 for Javascript and noticed that we might be able to slim down the dependency tree for the `js` build a bit. 
Most of the system integration does not make sense in WASM, and we can make it optional.
This PR makes `dirs`, `keyring`, and `netrc-rs` crates optional.

feat: make rattler_networking system integration optional

---

crates/rattler_conda_types/src/repo_data/patches.rs
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__patches__test__null_values.snap
crates/rattler_conda_types/src/repo_data/snapshots/rattler_conda_types__repo_data__patches__test__patch_tracked_features.snap
test-data/channels/patch/linux-64/patch_instructions_5.json
test-data/channels/patch/linux-64/repodata_from_packages_5.json

We found out that `track_features` in repodata patches can be `null`. This would effectively remove all tracked features. At the moment though this field is ignored by our implementation which means its not actually applied at all. This PR fixes that.

fix: allow track_features to be patched to null

---

crates/rattler_networking/src/oci_middleware.rs
crates/rattler_repodata_gateway/src/gateway/builder.rs
py-rattler/rattler/networking/client.py
py-rattler/src/error.rs
py-rattler/src/networking/client.rs
py-rattler/src/networking/mod.rs
py-rattler/src/repo_data/gateway.rs

Fixes #1442 
This PR is an attempt at fixing #1442.
Changes on the rust side:
* Set a default user-agent in `GatewayBuilder.finish()` if no client is provided.
Changes on the Python side:
* Add a `headers` keyword argument to `rattler.Client` to allow setting HTTP headers.
* If no `headers` are provided to `rattler.Client`, set the default user-agent to `py-rattler/<version>`.
* A PyClient will be created if no client is passed to `rattler.Gateway`, ensuring that
the default user-agent is `py-rattler/<version>`.

feat: Set default User-Agent if not provided

---

crates/rattler_upload/Cargo.toml

Add metadata "authors" and "description"  for 'rattler_upload' crate

fix: fix metadata "authors" and "description" missing in 'rattler_upload' crate

---

crates/rattler_repodata_gateway/src/sparse/mod.rs

This changes the way urls are constructed for package records that incorrectly report their `subdir`. When constructing the url we now take the subdir from where the repodata was downloading instead of the subdir that is recorded in the package record.
Fixes https://github.com/prefix-dev/pixi/issues/4164

fix: use channel `subdir` instead of the one from the record

---

crates/rattler_conda_types/src/package/index.rs
crates/rattler_conda_types/src/repo_data/mod.rs
crates/rattler_index/src/lib.rs
crates/rattler_lock/src/parse/models/v5/conda_package_data.rs
crates/rattler_lock/src/parse/models/v6/conda_package_data.rs
crates/rattler_lock/src/parse/v3.rs
crates/rattler_repodata_gateway/src/gateway/query.rs
crates/rattler_solve/src/resolvo/mod.rs
crates/rattler_solve/tests/backends.rs
js-rattler/crate/solve.rs
py-rattler/src/record.rs

We currently do not properly index extras because we fill the field with a `default` hash map. This PR fixes it.

fix: indexing `extra-depends`

---

pixi.lock
pixi.toml

to avoid locally:
```
2025-07-23T11:14:02.294041+01:00 ERROR can't load standard library, try installing `rust-src` sysroot_path=/Users/lucascolley/ghq/github.com/lucascolley/rattler/.pixi/envs/default
```
same as https://github.com/prefix-dev/rattler-build/pull/1374, https://github.com/prefix-dev/pixi/blob/463ae37fc728b6b518cf73d5d5803f84964bc474/pixi.toml#L161

chore(deps): add `rust-src` for rust-analyzer

---

crates/rattler_package_streaming/Cargo.toml
crates/rattler_package_streaming/src/read.rs
crates/rattler_package_streaming/tests/extract.rs

We need to fix reading small tar.bz2 archives to the end. The `openmp` archive is only ~8kB and it looks like we are not reading the last ~4 or so bytes, resulting in a wrong hash being computed. 
Since we recently started to always strictly validate package hashes, this is failing in `pixi` and other downstream users.
When I added some debug logging, it says:
`bytes_read: 8192`
while the entire archive is `8198` bytes long (so missing 6 bytes at the end).

fix: tar.bz2 archives not read to end resulting in wrong hash

---

crates/rattler_cache/src/package_cache/mod.rs

The error message gave no hint which package had a hash mismatch

fix: improve hash mismatch warning to include package path

---

crates/rattler_cache/src/package_cache/mod.rs
crates/rattler_package_streaming/src/lib.rs
crates/rattler_package_streaming/src/read.rs

When experiencing hash mismatch errors, it's quite difficult to debug them due to the lack of information in the error message. I've added a few extra fields in the error message like:
* The `url` we tried to download from
* The `destination` we tried to download to
* The `total_size` of the file we downloaded
As part of this PR, I've unified the way hashes were calculated by removing the `compute_hashes` function and replaced it with `process_with_hashing`, which makes the other functions more neat.

feat: Provide more details when hash mismatch occurs

---

crates/rattler_upload/src/lib.rs
crates/rattler_upload/src/upload/opt.rs
crates/rattler_upload/src/utils/tool_configuration.rs

Let `UploadOpts` support `auth_store` field, which allows `pixi` to pass auth_store into `rattler_upload`. 
In the original `get_auth_store` function, `rattler_networking::AuthenticationStorage::from_env_and_defaults()` only works in `rattler_build`, but in `pixi` it doesn't work. 
The reason behind this: 
1) auth_store logic is different in `pixi` and `rattler_build`:
In `pixi`, we can see it will read from Config. 
But in `rattler_build`, it doesn't have this kind of logic. (`rattler_upload` crate is firstly migrated from `rattler_build`)
2) the default key for `rattler_networking::AuthenticationStorage::from_env_and_defaults()` is hardcoded as "rattler".

feat: update `UploadOpts` and `get_auth_store`

---

crates/rattler-bin/src/commands/create.rs
crates/rattler/src/install/installer/mod.rs
crates/rattler/src/install/transaction.rs
crates/rattler/src/install/unlink.rs
py-rattler/rattler/install/installer.py
py-rattler/src/installer.rs

This PR adds the ability to ignore packages, so to basically keep them around in the prefix even though they are no longer requested. This is useful to add the ability to do a partial prefix installation or re-installation.

feat: ability to ignore packages in the installer

---

crates/rattler/src/install/clobber_registry.rs
crates/rattler/src/install/installer/mod.rs
crates/rattler/src/install/link_script.rs
crates/rattler/src/install/transaction.rs

This PR moves the construction of several objects after checking if the transaction is empty. This should make installing of empty transaction much faster.

perf(rattler): reduce overhead if transaction is empty

---

crates/rattler_menuinst/src/linux.rs
crates/rattler_menuinst/src/snapshots/rattler_menuinst__linux__tests__installation.snap

This fixes a couple of problems with our linux menuinst implementation:
- `bash -c` is only need if pre-command is used to chain with `&&`, I dropped it since it makes it harder for launchers to parse `%F` and similar
- The pre-command is supposed to be used *before* the environment is activated, so I fixed that
- fix quoting
- clean up code a bit
I tested it locally with `pixi global` and Zed and it works for me. Also added a couple of tests.

fix(menuinst): improve linux

---

.github/workflows/release-rust.yaml
crates/coalesced_map/src/lib.rs

Adds a `CoalescedMap::clear` function that removes any cached values from the map.

feat: add clear on coalesced_map

---

crates/rattler_menuinst/src/linux.rs
crates/rattler_menuinst/src/snapshots/rattler_menuinst__linux__tests__installation.snap

While quoting each argument is reasonable in general, unfortunately nautilus cannot deal with quoted special arguments like "%f". This PR changes behaviour so that these arguments are not quoted. I tested this locally with Pixi and it works as expected.
@lucascolley

fix: menuinst on linux with `%` command
